// Canvas fallback for software WebGL: inverse sampling moves the cloud pixels, never overlays a trail.
export async function mountCloudCanvas(host,urls){
 const fine=matchMedia('(hover:hover) and (pointer:fine)'),reduce=matchMedia('(prefers-reduced-motion:reduce)'),transparent=matchMedia('(prefers-reduced-transparency:reduce)'),forced=matchMedia('(forced-colors:active)');
 const images=await Promise.all(urls.map(async src=>{const image=new Image();image.src=src;await image.decode();return image;}));
 const faded=images.map((image,i)=>{if(!i)return image;const c=document.createElement('canvas');c.width=image.width;c.height=image.height;const x=c.getContext('2d');x.drawImage(image,0,0);x.globalCompositeOperation='destination-in';const g=x.createLinearGradient(0,0,0,image.height*.16);g.addColorStop(0,'#0000');g.addColorStop(1,'#000');x.fillStyle=g;x.fillRect(0,0,c.width,c.height);return c;});
 const canvas=document.createElement('canvas'),base=document.createElement('canvas');canvas.className='cloud-flow-canvas';canvas.setAttribute('aria-hidden','true');host.append(canvas);host.classList.add('is-flowing');
 const lens=document.createElement('canvas');lens.className='cloud-sand-lens';lens.setAttribute('aria-hidden','true');host.append(lens);const ink=lens.getContext('2d',{willReadFrequently:true}),snapshot=document.createElement('canvas');let lensX=0,lensY=0;
 const ctx=canvas.getContext('2d',{alpha:false,willReadFrequently:true}),bg=base.getContext('2d',{alpha:false,willReadFrequently:true});let raf=0,running=false,frames=0,emissions=0,scroll=scrollY,targetScroll=scrollY,last=null,lastTime=0,stamps=[],baseProgress=-1,baseBuilds=0,basePixels=null,alive=true;
 const reduced=()=>reduce.matches||document.body.classList.contains('motion-off'),visible=()=>alive&&!document.hidden&&!transparent.matches&&!forced.matches,allowed=()=>visible()&&fine.matches&&!reduced();
 const progress=()=>reduced()?0:Math.max(0,Math.min(1,scroll/Math.max(1,document.documentElement.scrollHeight-innerHeight)));
 function paintBase(p){if(p===baseProgress)return;const sx=base.width/innerWidth,sy=base.height/innerHeight,span=Math.max(innerHeight*1.65,innerWidth*1.5),step=span*.84,total=span+2*step,offset=p*(total-innerHeight),w=span*2/3;
  bg.imageSmoothingEnabled=false;bg.fillStyle='#cfdfeb';bg.fillRect(0,0,base.width,base.height);for(let i=0;i<3;i++)bg.drawImage(faded[i],(innerWidth-w)*.5*sx,(step*i-offset)*sy,w*sx,span*sy);baseProgress=p;basePixels=null;baseBuilds++;
 }
 function draw(){const p=progress(),changed=p!==baseProgress;paintBase(p);ctx.imageSmoothingEnabled=false;if(changed)ctx.drawImage(base,0,0);const now=performance.now(),sx=canvas.width/innerWidth,sy=canvas.height/innerHeight;stamps=stamps.filter(s=>now-s.time<600);const cell=1;
  if(!reduced()&&stamps.length){const bounds={l:canvas.width,t:canvas.height,r:0,b:0};for(const s of stamps){bounds.l=Math.min(bounds.l,(s.x-84)*sx);bounds.r=Math.max(bounds.r,(s.x+84)*sx);bounds.t=Math.min(bounds.t,(s.y-84)*sy);bounds.b=Math.max(bounds.b,(s.y+84)*sy);}
   lensX=Math.max(0,Math.floor(bounds.l/cell)*cell);lensY=Math.max(0,Math.floor(bounds.t/cell)*cell);const right=Math.min(canvas.width,Math.ceil(bounds.r/cell)*cell),bottom=Math.min(canvas.height,Math.ceil(bounds.b/cell)*cell);lens.width=Math.max(1,right-lensX);lens.height=Math.max(1,bottom-lensY);lens.style.cssText='display:block;left:'+lensX/sx+'px;top:'+lensY/sy+'px;width:'+lens.width/sx+'px;height:'+lens.height/sy+'px';ink.imageSmoothingEnabled=false;if(!basePixels)basePixels=new Uint32Array(bg.getImageData(0,0,base.width,base.height).data.buffer);const patch=ink.createImageData(lens.width,lens.height),pixels=new Uint32Array(patch.data.buffer);for(let y=lensY;y<bottom;y+=cell)for(let x=lensX;x<right;x+=cell){let dx=0,dy=0;const px=(x+.5)/sx,py=(y+.5)/sy;for(const s of stamps){const d=Math.hypot(px-s.x,py-s.y)/84;if(d>=1)continue;const age=(now-s.time)/600,falloff=(1-d)*(1-d)*(1-age)*(1-age);dx+=s.dx*falloff;dy+=s.dy*falloff;}dx=Math.max(-14,Math.min(14,dx));dy=Math.max(-14,Math.min(14,dy));if(Math.abs(dx)+Math.abs(dy)<.12)continue;const cw=Math.min(cell,canvas.width-x),ch=Math.min(cell,canvas.height-y),u=Math.max(0,Math.min(base.width-cw,x-dx*sx)),v=Math.max(0,Math.min(base.height-ch,y-dy*sy));pixels[(y-lensY)*lens.width+x-lensX]=basePixels[Math.round(v)*base.width+Math.round(u)];}ink.putImageData(patch,0,0);
  }else{lens.style.display='none';}frames++;
 }
 function stop(){cancelAnimationFrame(raf);raf=0;running=false;stamps=[];last=null;scroll=targetScroll=scrollY;if(visible())draw();}
 function resize(){canvas.width=base.width=Math.ceil(innerWidth/1.5);canvas.height=base.height=Math.ceil(innerHeight/1.5);baseProgress=-1;stop();}
 function frame(){raf=0;if(!visible()){stop();return;}running=true;if(reduced())scroll=targetScroll;else scroll+=(targetScroll-scroll)*.20;if(Math.abs(targetScroll-scroll)<.1)scroll=targetScroll;if(reduced())stamps=[];draw();if(stamps.length||Math.abs(targetScroll-scroll)>.1)raf=requestAnimationFrame(frame);else running=false;}
 function wake(){if(!raf&&visible())raf=requestAnimationFrame(frame);}
 document.addEventListener('pointermove',e=>{if(!allowed()||e.pointerType==='touch')return;const now=performance.now();if(last&&Math.hypot(e.clientX-last.x,e.clientY-last.y)<240){const dt=Math.max(12,Math.min(64,now-lastTime)),dx=Math.max(-7,Math.min(7,(e.clientX-last.x)/dt*8)),dy=Math.max(-7,Math.min(7,(e.clientY-last.y)/dt*8));if(Math.abs(dx)+Math.abs(dy)>.05){stamps.push({x:e.clientX,y:e.clientY,dx,dy,time:now});if(stamps.length>6)stamps.shift();emissions++;wake();}}last={x:e.clientX,y:e.clientY};lastTime=now;},{passive:true});
 addEventListener('scroll',()=>{targetScroll=scrollY;if(reduced())stop();else wake();},{passive:true});addEventListener('resize',resize);document.documentElement.addEventListener('pointerleave',()=>{last=null;});addEventListener('blur',stop);document.addEventListener('visibilitychange',()=>document.hidden?stop():resize());addEventListener('pagehide',()=>{stop();alive=false;});for(const m of[fine,reduce,transparent,forced])m.addEventListener('change',stop);document.querySelector('.reduce').addEventListener('click',stop);resize();
 return{stop,stats:()=>({mode:'canvas-inverse-sampling',backend:'software-webgl-fallback',renderSize:[canvas.width,canvas.height],active:running,emissions,allowed:allowed(),frames,scroll,progress:progress(),sceneIndex:Math.min(2,Math.floor(progress()*3)),sources:3,mirrored:false,looped:false,maxDisplacement:14,reduced:reduced(),baseBuilds,localPatch:[lens.width,lens.height]}),signature:()=>{draw();snapshot.width=canvas.width;snapshot.height=canvas.height;const test=snapshot.getContext('2d',{willReadFrequently:true});test.drawImage(canvas,0,0);if(stamps.length)test.drawImage(lens,lensX,lensY);const bytes=test.getImageData(0,0,canvas.width,canvas.height).data;let h=2166136261;for(let i=0;i<bytes.length;i+=16)h=Math.imul(h^bytes[i],16777619);return h>>>0;}};
}
