const photoSlider=document.querySelector('.photo-slider');let heroFront=Number(document.querySelector('.stage').dataset.front||0),photoDrag=false;const cleanTitle=s=>s.replace(/^(占位作品|占位文章)[:：]/,'').replace(/^(Placeholder post|Placeholder)[:：]\s*/i,'');
function syncHero(){heroFront=Number(document.querySelector('.stage').dataset.front||0);photoSlider.setAttribute('aria-valuenow',String(heroFront));photoSlider.setAttribute('aria-valuetext',tr(...[['海岸纸卡 / 作品页','Coast card / Works'],['森林纸卡 / 文字页','Forest card / Writing'],['山间纸卡 / 探索页','Mountain card / Explore']][heroFront]));photoSlider.querySelectorAll('.photo-tick').forEach((e,i)=>e.classList.toggle('current',i===heroFront));document.querySelector('.works-total').textContent=String(content[lang].works.length).padStart(2,'0');document.querySelectorAll('[data-note-page]').forEach(b=>b.setAttribute('aria-pressed',String(+b.dataset.notePage===learningPage)));}
function chooseHero(i){i=Math.max(0,Math.min(2,i));if(index>=0){detail=null;window.selectPaper(i);}else window.setFrontPaper(i);syncHero();}
const heroObserver=new MutationObserver(syncHero);heroObserver.observe(document.querySelector('.stage'),{attributes:true,attributeFilter:['data-front']});new ResizeObserver(syncHero).observe(photoSlider);
function photoIndex(e){const r=photoSlider.getBoundingClientRect();if(photoSlider.getAttribute('aria-orientation')==='horizontal')return Math.round(Math.max(0,Math.min(1,(e.clientX-r.left-22)/(r.width-44)))*2);return Math.round(Math.max(0,Math.min(1,(e.clientY-r.top-18)/(r.height-36)))*2);}photoSlider.onpointerdown=e=>{if(e.button!==0)return;e.preventDefault();photoDrag=true;photoSlider.focus({preventScroll:true});photoSlider.setPointerCapture(e.pointerId);chooseHero(photoIndex(e));};photoSlider.onpointermove=e=>{if(photoDrag&&photoIndex(e)!==heroFront)chooseHero(photoIndex(e));};photoSlider.onpointerup=photoSlider.onpointercancel=()=>photoDrag=false;photoSlider.onkeydown=e=>{if(['ArrowUp','ArrowLeft','ArrowDown','ArrowRight','Home','End'].includes(e.key)){e.preventDefault();chooseHero(e.key==='Home'?0:e.key==='End'?2:heroFront+(['ArrowDown','ArrowRight'].includes(e.key)?1:-1));}};
document.querySelectorAll('[data-work-filter]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-work-filter]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));document.querySelectorAll('[data-work-kind]').forEach(c=>c.hidden=b.dataset.workFilter==='video'&&c.dataset.workKind!=='video');});document.querySelectorAll('[data-work-view]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-work-view]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));document.querySelector('.work-grid').classList.toggle('view-list',b.dataset.workView==='list');});document.querySelectorAll('[data-work-video]').forEach(b=>b.onclick=()=>{detail={slug:b.dataset.workVideo};window.selectPaper(0);document.querySelector('.video-load')?.click();});const legacyWorkPreview=document.querySelector('[data-work-preview]');if(legacyWorkPreview)legacyWorkPreview.onclick=()=>{const dialog=document.querySelector('.explore-dialog');exploreState='work-preview';exploreBody.innerHTML='<h2>'+tr('封面图像试样','Cover image study')+'</h2><div class="atlas-photo photo-ocean"></div><p>'+tr('CC0 公共纸卡素材，用于封面展示试样，非个人作品。','CC0 public postcard asset used as a cover study, not personal work.')+'</p>';explore.showModal();};document.querySelectorAll('[data-note-page]').forEach(b=>b.onclick=()=>{learningPage=+b.dataset.notePage;updateLearning();syncHero();});const oldNext=document.querySelector('.learning-next').onclick,oldPrev=document.querySelector('.learning-prev').onclick;document.querySelector('.learning-next').onclick=()=>{oldNext();syncHero();};document.querySelector('.learning-prev').onclick=()=>{oldPrev();syncHero();};const controlsLanguage=document.querySelector('.language').onclick;document.querySelector('.language').onclick=()=>{controlsLanguage();syncHero();};syncHero();
// Actual content states, with Motion feedback shared across every chapter.
function settleIn(nodes){}
document.querySelectorAll('[data-reading-view]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-reading-view]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));document.querySelector('.writing-shelf').classList.toggle('index-view',b.dataset.readingView==='list');settleIn([...document.querySelectorAll('.writing-list button')]);});
document.querySelectorAll('[data-repo-filter]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-repo-filter]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));const folders=[...document.querySelectorAll('[data-repo-kind]')];folders.forEach(x=>x.hidden=b.dataset.repoFilter!=='all'&&x.dataset.repoKind!==b.dataset.repoFilter);settleIn(folders.filter(x=>!x.hidden));});
// Each object answers a different action; don't animate the whole page identically.
const navLens=document.querySelector('.nav-lens'),navRoot=document.querySelector('.nav-links');
new MutationObserver(()=>document.querySelectorAll('.nav [data-open]').forEach(b=>b.setAttribute('aria-expanded',String(index===+b.dataset.open)))).observe(document.querySelector('.look'),{attributes:true,attributeFilter:['class']});
const photoStrip=document.querySelector('.photo-strip');let albumPosition=0;
function moveAlbum(delta){albumPosition=Math.max(0,Math.min(2,albumPosition+delta));const target=photoStrip.children[albumPosition];photoStrip.scrollTo({left:target.offsetLeft-photoStrip.children[0].offsetLeft,behavior:reduced()?'instant':'smooth'});}
document.querySelector('.album-prev').onclick=()=>moveAlbum(-1);document.querySelector('.album-next').onclick=()=>moveAlbum(1);
explore.addEventListener('close',()=>{document.querySelector('[data-explore="'+exploreState+'"]')?.focus({preventScroll:true});});function paintProgress(){seek.style.setProperty('--played',(Number(seek.value)/24*100)+'%');requestAnimationFrame(paintProgress);}paintProgress();
const designTablist=document.querySelector('.design-tabs');designTablist.setAttribute('role','tablist');designTablist.setAttribute('aria-label',tr('设计试样分类','Design study categories'));const designTabs=[...designTablist.children],designPanel=document.querySelector('.design-preview');designPanel.id='design-study-panel';designPanel.setAttribute('role','tabpanel');function syncDesignTabs(){designTabs.forEach((b,i)=>{b.id='design-tab-'+i;b.setAttribute('role','tab');b.setAttribute('aria-controls',designPanel.id);const selected=b.getAttribute('aria-pressed')==='true';b.setAttribute('aria-selected',String(selected));b.tabIndex=selected?0:-1;if(selected)designPanel.setAttribute('aria-labelledby',b.id);});}designTabs.forEach((b,i)=>{b.addEventListener('click',syncDesignTabs);b.addEventListener('keydown',e=>{if(!['ArrowLeft','ArrowRight','Home','End'].includes(e.key))return;e.preventDefault();const next=e.key==='Home'?0:e.key==='End'?2:(i+(e.key==='ArrowRight'?1:2))%3;designTabs[next].focus();designTabs[next].click();});});syncDesignTabs();
function syncAlbumControls(){const first=photoStrip.children[0];let nearest=0,distance=Infinity;[...photoStrip.children].forEach((e,i)=>{const d=Math.abs(photoStrip.scrollLeft-(e.offsetLeft-first.offsetLeft));if(d<distance){distance=d;nearest=i;}});albumPosition=nearest;document.querySelector('.album-prev').disabled=nearest===0;document.querySelector('.album-next').disabled=nearest===2;}
photoStrip.addEventListener('scroll',syncAlbumControls,{passive:true});syncAlbumControls();document.querySelectorAll('.nav [data-open]').forEach(b=>b.setAttribute('aria-expanded','false'));

// The same three marks stay available inside the expanded card header on every screen.
(()=>{const holder=document.querySelector('.photo-ruler'),home=document.querySelector('.look'),head=document.querySelector('.reader-head'),marks=[...photoSlider.querySelectorAll('.photo-tick')],original=marks.map(e=>e.style.cssText);function place(){const opened=home.classList.contains('open');const destination=opened?head:home;if(holder.parentElement!==destination)destination.insertBefore(holder,opened?head.querySelector('.close'):home.querySelector('.hint'));photoSlider.setAttribute('aria-orientation',opened?'horizontal':'vertical');marks.forEach((e,i)=>e.style.cssText=opened?'top:22px;left:'+(22+i*44)+'px;bottom:auto;transform:translateX(-50%)':original[i]);}new MutationObserver(place).observe(home,{attributes:true,attributeFilter:['class']});place();})();
