// Plyr is the real player, not a drawn player facade. Local PCM study stays offline.
const iconRoot=document.createElement('div');iconRoot.hidden=true;iconRoot.innerHTML=window.PAPER_PLAYER_ICONS;document.body.append(iconRoot);
const paperPlayer=new Plyr(audio,{controls:['play','current-time','duration','mute'],loadSprite:false,iconUrl:'',storage:{enabled:false},tooltips:{controls:true,seek:true},i18n:{play:'Play',pause:'Pause',mute:'Mute',unmute:'Unmute',seek:'Seek',volume:'Volume',currentTime:'Current time',duration:'Duration'}});window.paperPlayer=paperPlayer;
// Native image slides retain the source thumbnail for the opening and closing zoom.
let activeGallery=null;window.paperGalleryOpen=false;showPhoto=function(i){if(explore.open)explore.close();photoPage=(i+photos.length)%photos.length;if(activeGallery){activeGallery.goTo(photoPage);return;}const gallery=new PaperGallery.default({dataSource:photos.map((cls,n)=>({src:window.PAPER_PRINT_CACHE.images[cls],msrc:window.PAPER_PRINT_CACHE.images[cls],width:600,height:400,alt:tr(...photoNames[n])+' — CC0'})),index:photoPage,bgOpacity:.94,showHideAnimationType:reduced()?'none':'zoom',showAnimationDuration:reduced()?0:360,hideAnimationDuration:reduced()?0:300,easing:'cubic-bezier(.2,0,0,1)',arrowKeys:true,wheelToZoom:false,zoom:false});let queuedClose=false;const nativeClose=gallery.close.bind(gallery);gallery.close=()=>{if(gallery.opener.isOpening){queuedClose=true;return;}nativeClose();};gallery.on('openingAnimationEnd',()=>{if(queuedClose){queuedClose=false;nativeClose();}});gallery.addFilter('thumbEl',(el,itemData,n)=>document.querySelector('[data-photo="'+n+'"] .atlas-photo'));gallery.on('uiRegister',()=>gallery.ui.registerElement({name:'study-caption',order:9,isButton:false,appendTo:'root',onInit:(el,pswp)=>{el.className='gallery-study-caption';const paint=()=>{el.textContent=pswp.currSlide?.data.alt||tr(...photoNames[photoPage])+' — CC0';};pswp.on('change',paint);paint();}}));gallery.on('change',()=>{photoPage=gallery.currIndex;});gallery.on('destroy',()=>{activeGallery=null;window.paperGalleryOpen=false;document.querySelector('[data-photo="'+photoPage+'"]')?.focus({preventScroll:true});});window.paperGalleryOpen=true;activeGallery=gallery;gallery.init();};
window.paperGallery={stats:()=>({open:!!activeGallery,index:activeGallery?.currIndex,type:activeGallery?.options.showHideAnimationType,opening:activeGallery?.opener.isOpening,closing:activeGallery?.opener.isClosing,bounds:activeGallery?.currSlide?.content.element?.getBoundingClientRect().toJSON()})};
document.querySelectorAll('[data-work-filter]').forEach(b=>b.addEventListener('click',()=>document.querySelector('.work-grid').classList.toggle('only-video',b.dataset.workFilter==='video')));
// Learning uses the same accessible tab contract as the design samples.
const noteTablist=document.querySelector('.note-page-tabs');noteTablist.setAttribute('role','tablist');const noteTabs=[...noteTablist.querySelectorAll('button')],notePanel=document.createElement('div');notePanel.id='learning-panel';notePanel.setAttribute('role','tabpanel');const noteSheet=document.querySelector('.learning-paper');[...noteSheet.children].filter(n=>!n.matches('.page-number,.note-page-tabs')).forEach(n=>notePanel.append(n));noteSheet.append(notePanel);function syncNoteTabs(){notePanel.setAttribute('aria-labelledby','note-tab-'+learningPage);noteTabs.forEach((b,i)=>{b.id='note-tab-'+i;b.setAttribute('role','tab');b.setAttribute('aria-selected',String(learningPage===i));b.tabIndex=learningPage===i?0:-1;b.setAttribute('aria-controls',notePanel.id);});}noteTabs.forEach((b,i)=>{b.addEventListener('click',syncNoteTabs);b.addEventListener('keydown',e=>{if(!['ArrowLeft','ArrowRight','Home','End'].includes(e.key))return;e.preventDefault();const j=e.key==='Home'?0:e.key==='End'?2:(i+(e.key==='ArrowRight'?1:2))%3;noteTabs[j].focus();noteTabs[j].click();});});document.querySelectorAll('.learning-next,.learning-prev').forEach(b=>b.addEventListener('click',syncNoteTabs));syncNoteTabs();

// Compact notched controls: one visual language, no long track or numerical chrome.
const transport=document.createElement('div');transport.className='transport-controls';transport.innerHTML='<div class="sound-position" role="slider" tabindex="0" aria-label="Playback position" aria-valuemin="0" aria-valuemax="24"><div class="sound-ticks">'+Array.from({length:16},()=>'<i></i>').join('')+'</div></div><div class="volume-dial" role="slider" tabindex="0" aria-label="Volume" aria-valuemin="0" aria-valuemax="100"><span class="dial-cap"><i></i></span></div>';document.querySelector('.player-deck').append(transport);
const positionControl=transport.querySelector('.sound-position'),volumeControl=transport.querySelector('.volume-dial');
function paintAudioControls(){const ratio=audio.currentTime/(audio.duration||24);positionControl.setAttribute('aria-valuenow',audio.currentTime.toFixed(1));positionControl.setAttribute('aria-valuetext',Math.round(audio.currentTime)+' / '+Math.round(audio.duration||24)+' s');[...positionControl.querySelectorAll('i')].forEach((n,i)=>n.classList.toggle('lit',i/15<=ratio));volumeControl.style.setProperty('--angle',(-135+audio.volume*270)+'deg');volumeControl.setAttribute('aria-valuenow',String(Math.round(audio.volume*100)));}
function bindCompactControl(el,read,write,max,fromPointer){let held=false;el.addEventListener('pointerdown',e=>{if(e.button!==0)return;held=true;el.focus({preventScroll:true});el.setPointerCapture(e.pointerId);write(fromPointer(e));});el.addEventListener('pointermove',e=>{if(held)write(fromPointer(e));});['pointerup','pointercancel','lostpointercapture'].forEach(name=>el.addEventListener(name,()=>held=false));el.addEventListener('keydown',e=>{const step=e.key==='ArrowRight'||e.key==='ArrowUp'?1:e.key==='ArrowLeft'||e.key==='ArrowDown'?-1:0;if(step||e.key==='Home'||e.key==='End'){e.preventDefault();write(e.key==='Home'?0:e.key==='End'?max():read()+step*max()/20);}});}
bindCompactControl(positionControl,()=>audio.currentTime,v=>{audio.currentTime=Math.max(0,Math.min(audio.duration||24,v));paintAudioControls();},()=>audio.duration||24,e=>{const r=positionControl.getBoundingClientRect();return(e.clientX-r.left)/r.width*(audio.duration||24);});
bindCompactControl(volumeControl,()=>audio.volume,v=>{audio.volume=Math.max(0,Math.min(1,v));paintAudioControls();},()=>1,e=>{const r=volumeControl.getBoundingClientRect();if(Math.hypot(e.clientX-r.left-r.width/2,e.clientY-r.top-r.height/2)<6)return audio.volume;let angle=Math.atan2(e.clientX-r.left-r.width/2,-(e.clientY-r.top-r.height/2))*180/Math.PI;return(angle+135)/270;});
['timeupdate','volumechange','loadedmetadata','seeked'].forEach(n=>audio.addEventListener(n,paintAudioControls));paintAudioControls();
// Material illumination follows the hand; it stops when the pointer leaves.
document.querySelectorAll('.work-image,.paper-sample,.design-art').forEach(surface=>{surface.classList.add('material-light');surface.addEventListener('pointermove',e=>{if(reduced()||e.pointerType==='touch')return;const r=surface.getBoundingClientRect(),x=(e.clientX-r.left)/r.width,y=(e.clientY-r.top)/r.height;surface.style.setProperty('--light-x',x*100+'%');surface.style.setProperty('--light-y',y*100+'%');surface.classList.add('lit-surface');});surface.addEventListener('pointerleave',()=>surface.classList.remove('lit-surface'));});
const photoRail=document.querySelector('.photo-strip');photoRail.addEventListener('scroll',()=>{const max=photoRail.scrollWidth-photoRail.clientWidth;document.querySelector('.album-prev').disabled=photoRail.scrollLeft<2;document.querySelector('.album-next').disabled=photoRail.scrollLeft>max-2;},{passive:true});
// The cover is a small stack: pointer movement changes relative depth, not page position.
const coverStack=document.querySelector('.work-art-open');const coverPrints=[...coverStack.querySelectorAll('.study-photo')];coverStack.addEventListener('pointermove',e=>{if(reduced()||e.pointerType==='touch')return;const r=coverStack.getBoundingClientRect(),x=(e.clientX-r.left)/r.width-.5,y=(e.clientY-r.top)/r.height-.5;coverPrints.forEach((print,i)=>{print.style.transform='translate('+x*(i?10:-5)+'px,'+y*(i?8:-4)+'px) rotate('+((i?4:-4)+x*(i?3:-2))+'deg)';});});coverStack.addEventListener('pointerleave',()=>coverPrints.forEach(print=>print.style.removeProperty('transform')));document.querySelector('.reduce').addEventListener('click',()=>coverPrints.forEach(print=>print.style.removeProperty('transform')));

const notebookHeader=document.createElement('div');notebookHeader.className='notebook-header';noteSheet.prepend(notebookHeader);notebookHeader.append(noteSheet.querySelector('.page-number'),noteTablist);
const noteExamples=[['字、图和间距','Type, images and spacing','同一页的三种关系','Three relationships on a page'],['纹理、光与纸面','Texture, light and paper','观察表面，再调整强弱','Observe the surface, then its intensity'],['前后、速度与停下','Depth, speed and settling','切换与展开分开练习','Practice switching and opening separately']];
const noteDetails=document.createElement('div');noteDetails.className='note-details';notePanel.querySelector('.learning-summary').after(noteDetails);
function fillNoteDetails(){const d=noteExamples[learningPage];noteDetails.innerHTML='<div><span data-zh="观察" data-en="Observe">'+tr('观察','Observe')+'</span><p>'+esc(tr(d[0],d[1]))+'</p></div><div><span data-zh="练习" data-en="Exercise">'+tr('练习','Exercise')+'</span><p>'+esc(tr(d[2],d[3]))+'</p></div>';}fillNoteDetails();
document.querySelectorAll('[data-note-page],.learning-next,.learning-prev').forEach(b=>b.addEventListener('click',fillNoteDetails));const continuityLanguage=document.querySelector('.language').onclick;document.querySelector('.language').onclick=()=>{continuityLanguage();fillNoteDetails();};
const chapterButtons=document.createElement('div');chapterButtons.className='episode-chapters';chapterButtons.innerHTML=[['00:00','淡入','Fade in',0],['00:08','音色交叠','Layered tones',8],['00:16','渐弱至结束','Fade out',16]].map(d=>'<button data-sound-chapter="'+d[3]+'"><span>'+d[0]+'</span><span data-zh="'+d[1]+'" data-en="'+d[2]+'">'+tr(d[1],d[2])+'</span><i aria-hidden="true">↗</i></button>').join('');document.querySelector('.player-deck').after(chapterButtons);chapterButtons.querySelectorAll('button').forEach(b=>b.addEventListener('click',async()=>{audio.currentTime=+b.dataset.soundChapter;await playAudio();}));audio.addEventListener('timeupdate',()=>chapterButtons.querySelectorAll('button').forEach(b=>{const active=Math.min(2,Math.floor(audio.currentTime/8))===+b.dataset.soundChapter/8;b.classList.toggle('active',active);b.setAttribute('aria-current',active?'true':'false');}));
document.querySelector('.reduce').addEventListener('click',()=>{if(reduced()){pauseRecord();document.querySelectorAll('.lit-surface').forEach(e=>e.classList.remove('lit-surface'));}else if(!audio.paused)resumeRecord();});
const futureNote=document.querySelector('.next-grid [data-explore=learning]');futureNote.onclick=()=>{learningPage=1;updateLearning(false);syncNoteTabs();syncHero();fillNoteDetails();openExplore('learning');};const futureMotion=document.querySelector('.next-grid [data-explore=design]');futureMotion.onclick=()=>{designTopic='motion';updateDesign(false);syncDesignTabs();openExplore('design');};
const exerciseTray=document.createElement('div');exerciseTray.className='exercise-tray';exerciseTray.innerHTML='<span data-zh="练习页 / 展示试样" data-en="Exercise / Display study">'+tr('练习页 / 展示试样','Exercise / Display study')+'</span><div><button aria-pressed="false" data-zh="字与图" data-en="Type & image">'+tr('字与图','Type & image')+'</button><button aria-pressed="false" data-zh="光与纸" data-en="Light & paper">'+tr('光与纸','Light & paper')+'</button><button aria-pressed="false" data-zh="前与后" data-en="Front & back">'+tr('前与后','Front & back')+'</button></div>';noteDetails.after(exerciseTray);exerciseTray.querySelectorAll('button').forEach(b=>b.addEventListener('click',()=>b.setAttribute('aria-pressed',String(b.getAttribute('aria-pressed')!=='true'))));
const exerciseStates=Array.from({length:3},()=>[false,false,false]);function syncExercises(){exerciseTray.querySelectorAll('button').forEach((b,i)=>b.setAttribute('aria-pressed',String(exerciseStates[learningPage][i])));}exerciseTray.querySelectorAll('button').forEach((b,i)=>b.addEventListener('click',()=>exerciseStates[learningPage][i]=b.getAttribute('aria-pressed')==='true'));document.querySelectorAll('[data-note-page],.learning-next,.learning-prev,.next-grid [data-explore=learning]').forEach(b=>b.addEventListener('click',syncExercises));
// Three live alternatives, with exactly the same material and component system.
const themeSwatches={blue:['#C7DDEC','#304F61','#F9FBFC','#DCE8EF'],ink:['#C6DCE8','#30455E','#EDF3F8','#D7E5ED'],mist:['#D0E1E6','#37535D','#F1F5F5','#E2EBEE']};function choosePalette(name){document.documentElement.dataset.palette=name;document.querySelectorAll('.palette-chooser [data-palette]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.palette===name)));[...document.querySelectorAll('.swatch-stack [data-copy]')].slice(0,4).forEach((b,i)=>{const color=themeSwatches[name][i];b.dataset.copy=color;b.style.setProperty('--swatch',color);b.textContent=color;});}document.querySelectorAll('.palette-chooser [data-palette]').forEach(b=>b.addEventListener('click',()=>choosePalette(b.dataset.palette)));choosePalette('blue');
document.querySelectorAll('.spread-label').forEach((bridge,i)=>{bridge.classList.add('chapter-bridge');const mark=document.createElement('i');mark.className='chapter-number';mark.textContent=String(i+1).padStart(2,'0');bridge.firstElementChild.prepend(mark);const track=document.createElement('i');track.className='chapter-connector';bridge.firstElementChild.after(track);});
const progress=document.createElement('div');progress.className='main-progress';progress.setAttribute('aria-hidden','true');document.body.append(progress);gsap.registerPlugin(ScrollTrigger);let pageMotionContext=null;
function installPageMotion(){pageMotionContext?.revert();pageMotionContext=null;if(reduced()||look.classList.contains('open')){progress.style.transform='scaleX(1)';return;}pageMotionContext=gsap.context(()=>{gsap.to(progress,{scaleX:1,ease:'none',scrollTrigger:{start:0,end:()=>ScrollTrigger.maxScroll(window),scrub:true}});gsap.timeline({scrollTrigger:{trigger:look,start:()=>look.getBoundingClientRect().top+scrollY,end:()=>look.getBoundingClientRect().bottom+scrollY,scrub:.45}}).to('.headline',{y:-65,opacity:.4,ease:'none'},0).to('.stage',{y:-40,ease:'none'},0).to('.hero-links',{y:-25,opacity:.3,ease:'none'},0);document.querySelectorAll('.chapter-connector').forEach(track=>gsap.fromTo(track,{scaleX:.2},{scaleX:1,ease:'none',scrollTrigger:{trigger:track.parentElement,start:()=>track.parentElement.getBoundingClientRect().top+scrollY-innerHeight*.95,end:()=>track.parentElement.getBoundingClientRect().top+scrollY-innerHeight*.55,scrub:.3}}));});ScrollTrigger.refresh();}
document.fonts.ready.then(installPageMotion);document.querySelector('.reduce').addEventListener('click',installPageMotion);mq.addEventListener('change',installPageMotion);document.querySelectorAll('[data-open],[data-entry],[data-post]').forEach(b=>b.addEventListener('click',()=>requestAnimationFrame(()=>ScrollTrigger.refresh())));let pageWasOpen=look.classList.contains('open');new MutationObserver(()=>{const now=look.classList.contains('open');if(now!==pageWasOpen){pageWasOpen=now;requestAnimationFrame(installPageMotion);}}).observe(look,{attributes:true,attributeFilter:['class']});window.addEventListener('pagehide',()=>pageMotionContext?.revert());window.paperPageMotion={refresh:()=>ScrollTrigger.refresh(),count:()=>ScrollTrigger.getAll().length,finishJump:()=>{ScrollTrigger.update();ScrollTrigger.getAll().forEach(t=>{t.getTween()?.progress?.(1);t.animation?.progress(t.progress);});}};
const themedExplore=openExplore;openExplore=function(key){themedExplore(key);if(key==='design'&&designTopic==='color')exploreBody.querySelector('p').textContent=themeSwatches[document.documentElement.dataset.palette].join(' / ');};
// Overflow navigation consumes the wheel only while it can actually move.
const chapterRail=document.querySelector('.section-map');chapterRail.addEventListener('wheel',e=>{if(e.ctrlKey)return;const max=chapterRail.scrollWidth-chapterRail.clientWidth;if(max<2)return;let delta=Math.abs(e.deltaX)>Math.abs(e.deltaY)?e.deltaX:e.deltaY;if(e.deltaMode===1)delta*=16;else if(e.deltaMode===2)delta*=chapterRail.clientWidth;const next=Math.max(0,Math.min(max,chapterRail.scrollLeft+delta));if(Math.abs(next-chapterRail.scrollLeft)<.5)return;e.preventDefault();chapterRail.scrollTo({left:next,behavior:'instant'});},{passive:false});chapterRail.addEventListener('focusin',e=>{const item=e.target.closest('a');if(!item)return;const r=item.getBoundingClientRect(),box=chapterRail.getBoundingClientRect();if(r.right>box.right)chapterRail.scrollLeft+=r.right-box.right+8;else if(r.left<box.left)chapterRail.scrollLeft-=box.left-r.left+8;});
// Cloud Flowmap now owns pointer disturbance; the old 1800-stroke fiber loop is retired.
window.paperFibers={stats:()=>({running:false,frames:0,allowed:false,layers:[]}),clear:()=>{}};
// A shared context connects the exhibition to the notebook, without inventing project notes.
(()=>{
const studies={
 site:{name:['个人网站','Personal website'],kind:['正在进行 / 本站设计','In progress / Site design'],note:['界面、材料与内容之间的关系。','Relationships between interface, materials and content.'],photo:'photo-city',page:1,topic:'color',entry:null},
 poster:{name:['海报系列','Poster series'],kind:['作品占位 / 视觉试样','Work placeholder / Visual study'],note:['从字与图的关系，接到排版练习。','From type and image to a typography exercise.'],photo:'photo-ocean',page:0,topic:'type',entry:'poster-series'},
 motion:{name:['动态影像','Moving image'],kind:['作品占位 / 交互试样','Work placeholder / Interaction study'],note:['从前后层次，接到切换与展开。','From spatial layers to switching and opening.'],photo:'photo-mountain',page:2,topic:'motion',entry:'motion-reel'}
};let context='site',view='connections';
const bench=document.createElement('section');bench.className='context-workbench';bench.setAttribute('aria-label','Related studies');bench.innerHTML=`
<div class="bench-top"><span class="bench-label" data-zh="关联工作台" data-en="Study desk">关联工作台</span><div class="context-switch" role="group" aria-label="Choose a study">${Object.entries(studies).map(([key,s])=>`<button data-context="${key}" aria-pressed="${key==='site'}" data-zh="${s.name[0]}" data-en="${s.name[1]}">${tr(...s.name)}</button>`).join('')}</div><span class="bench-status" data-zh="同一个上下文" data-en="One shared context">同一个上下文</span></div>
<div class="bench-body"><div class="bench-preview"><div class="preview-backing"></div><div class="preview-paper"><div class="atlas-photo photo-city"></div><span class="preview-caption"></span></div><span class="preview-pin" aria-hidden="true"></span><div class="preview-label"><span class="context-kind"></span><h3 class="context-name"></h3></div></div>
<div class="bench-inspector"><div class="inspector-tabs" role="tablist" aria-label="Study view"><button role="tab" id="bench-connections" data-bench-view="connections" aria-controls="bench-panel" aria-selected="true" tabindex="0" data-zh="关联路径" data-en="Connections">关联路径</button><button role="tab" id="bench-source" data-bench-view="source" aria-controls="bench-panel" aria-selected="false" tabindex="-1" data-zh="内容状态" data-en="Content status">内容状态</button></div><div id="bench-panel" role="tabpanel" aria-labelledby="bench-connections" class="inspector-panel"></div><div class="bench-footer"><span data-zh="选择会同步到下方过程册" data-en="Selection also updates the process book">选择会同步到下方过程册</span><button class="context-open"></button></div></div></div>`;
document.querySelector('.works-footer').after(bench);
const projectAttachment=document.createElement('div');projectAttachment.className='context-attachment';document.querySelector('.process-book').prepend(projectAttachment);
const projectEmpty=document.createElement('div');projectEmpty.className='context-empty';document.querySelector('.book-pages').after(projectEmpty);
for(const id of ['learning','design-notes','repos']){const tag=document.createElement('button');tag.className='context-receipt';tag.dataset.contextReturn='';tag.setAttribute('aria-label','Return to the study desk');document.getElementById(id).append(tag);}
document.querySelectorAll('.work-card').forEach((card,i)=>{const b=document.createElement('button');b.className='work-context-action';b.dataset.context=i?'motion':'poster';b.dataset.zh='接到工作台';b.dataset.en='Connect to desk';b.textContent=tr('接到工作台','Connect to desk');card.querySelector('.work-actions').append(b);const badge=document.createElement('span');badge.className='work-layer-label';badge.dataset.zh='预览 / 作品占位';badge.dataset.en='Preview / Placeholder';badge.textContent=tr('预览 / 作品占位','Preview / Placeholder');card.querySelector('.work-image').append(badge);});
function route(target){const s=studies[context];if(target==='learning'){learningPage=s.page;updateLearning(false);syncNoteTabs();fillNoteDetails();syncExercises();syncHero();}if(target==='design-notes'){designTopic=s.topic;updateDesign(false);syncDesignTabs();}if(target==='repos'){document.querySelector('[data-repo-filter="project"]').click();}goChapter(chapterIds.indexOf(target));}
function render(){const s=studies[context];document.body.dataset.study=context;
bench.querySelector('.context-name').textContent=tr(...s.name);bench.querySelector('.context-kind').textContent=tr(...s.kind);bench.querySelector('.preview-caption').textContent=tr('公共图像 · CC0 / 展示试样','Public image · CC0 / Display study');bench.querySelector('.preview-paper .atlas-photo').className='atlas-photo '+s.photo;
document.querySelectorAll('[data-context]').forEach(b=>{b.setAttribute('aria-pressed',String(b.dataset.context===context));b.classList.toggle('context-active',b.dataset.context===context);});
bench.querySelectorAll('[data-bench-view]').forEach(b=>{b.setAttribute('aria-selected',String(b.dataset.benchView===view));b.tabIndex=b.dataset.benchView===view?0:-1;});const panel=bench.querySelector('#bench-panel');panel.setAttribute('aria-labelledby','bench-'+view);
if(view==='connections'){panel.innerHTML='<p class="context-note">'+esc(tr(...s.note))+'</p><div class="connection-path">'+[
['projects','01','过程册','Process book',context==='site'?'当前网站的三段设计试样':'该作品的真实过程待补',context==='site'?'Three site design studies':'Real project process pending'],
['learning','02','学习页','Learning page',learningPages[s.page][0],['Space in typography','Looking at paper','A moving sheet'][s.page]],
['design-notes','03','设计试验','Design experiment',s.topic==='type'?'两级字形关系':s.topic==='color'?'蓝与纸面的关系':'切换与展开',s.topic==='type'?'Typography levels':s.topic==='color'?'Blue and paper':'Switching and opening']
].map(d=>'<button data-context-route="'+d[0]+'"><span class="path-step">'+d[1]+'</span><span><strong>'+tr(d[2],d[3])+'</strong><small>'+tr(d[4],d[5])+'</small></span><i aria-hidden="true">↗</i></button>').join('')+'</div>';
}else{panel.innerHTML='<div class="source-sheet"><span class="source-stamp">'+tr('展示试样','Display study')+'</span><h4>'+tr('有什么，还缺什么','Present and pending')+'</h4><p>'+tr(context==='site'?'本站设计记录和公开仓库可以查看；正式发布的手记尚未补齐。':'作品标题与正文来自原项目占位内容。关联练习是本轮设计试样，不代表真实创作过程。',context==='site'?'Site design studies and the public repository are available; published notes are still pending.':'Titles and text come from existing placeholders. Linked exercises are design studies, not the actual creative process.')+'</p><button data-context-route="'+(context==='site'?'repos':'projects')+'">'+tr(context==='site'?'查看实现 ↗':'查看待补内容 ↗',context==='site'?'View implementation ↗':'View pending content ↗')+'</button></div>';}
const open=bench.querySelector('.context-open');open.textContent=tr(s.entry?'打开作品 ↗':'查看网站记录 ↗',s.entry?'Open work ↗':'View site studies ↗');open.onclick=()=>{if(s.entry)document.querySelector('[data-entry="'+s.entry+'"]').click();else route('projects');};
projectAttachment.innerHTML='<span class="attachment-marker" aria-hidden="true"></span><span><small>'+tr('来自工作台','From the study desk')+'</small><strong>'+esc(tr(...s.name))+'</strong></span><button data-context-return>'+tr('换一个 ↗','Change ↗')+'</button>';
document.querySelector('.book-pages').hidden=context!=='site';document.querySelector('.process-meta').hidden=context!=='site';projectEmpty.hidden=context==='site';projectEmpty.innerHTML='<span class="empty-sheet-corner" aria-hidden="true"></span><small>'+tr('过程 / 待补','Process / Pending')+'</small><h3>'+tr('这一页留给真实过程','A page for the real process')+'</h3><p>'+tr('目前只有作品占位。先查看相关练习，之后把真实草稿、选择与复盘放到这里。','Only a work placeholder exists. Explore the related exercise now; add real drafts, decisions and reflections here later.')+'</p><button data-context-route="learning">'+tr('接着看学习页 ↗','Continue to the learning page ↗')+'</button>';
document.querySelectorAll('.context-receipt').forEach(b=>{b.innerHTML='<span aria-hidden="true">↳</span><span><small>'+tr('关联展示试样','Related display study')+'</small><strong>'+esc(tr(...s.name))+'</strong></span><i aria-hidden="true">↗</i>';});
}
function select(next){if(!studies[next])return;context=next;render();if(!reduced())bench.querySelector('.preview-paper').animate([{transform:'translateY(8px) rotate(-2deg)'},{transform:'translateY(0) rotate(-1deg)'}],{duration:360,easing:'cubic-bezier(.16,1,.3,1)'});}
document.addEventListener('click',e=>{const chooser=e.target.closest('[data-context]');if(chooser){select(chooser.dataset.context);if(chooser.classList.contains('work-context-action'))bench.scrollIntoView({behavior:reduced()?'instant':'smooth',block:'center'});}const next=e.target.closest('[data-context-route]');if(next)route(next.dataset.contextRoute);if(e.target.closest('[data-context-return]'))bench.scrollIntoView({behavior:reduced()?'instant':'smooth',block:'center'});const tab=e.target.closest('[data-bench-view]');if(tab){view=tab.dataset.benchView;render();}});
bench.querySelector('.inspector-tabs').addEventListener('keydown',e=>{if(!['ArrowLeft','ArrowRight','Home','End'].includes(e.key))return;e.preventDefault();view=e.key==='Home'?'connections':e.key==='End'?'source':view==='source'?'connections':'source';render();bench.querySelector('[aria-selected="true"]').focus();});
const priorLanguage=document.querySelector('.language').onclick;document.querySelector('.language').onclick=()=>{priorLanguage();render();};render();window.paperStudy={select,state:()=>({context,view}),route};
})();
// Unmodified MIT optical implementation is embedded before this script.
(()=>{
const transparency=matchMedia('(prefers-reduced-transparency:reduce)');const optical=[];
function mountGlass(el,options){if(!el||transparency.matches||matchMedia('(forced-colors:active)').matches)return null;const instance=PaperGlass.createLiquidGlass(el,{scale:-20,aberration:[0,.4,.8],border:.06,blur:4,displaceBlur:5,saturation:1.04,fallbackFilter:'blur(14px)',...options});optical.push(instance);return instance;}
const topNav=document.querySelector('.nav'),topOptic=document.createElement('i');topOptic.className='glass-optic';topOptic.setAttribute('aria-hidden','true');topNav.prepend(topOptic);window.paperGlassTop=mountGlass(topOptic,{borderRadius:28,scale:-12,aberration:[0,.15,.3],displaceBlur:2,width:topNav.offsetWidth,height:topNav.offsetHeight});
const groups=[];for(const selector of ['.context-switch','.design-tabs']){const root=document.querySelector(selector);const lens=document.createElement('span');lens.className='choice-glass';lens.setAttribute('aria-hidden','true');root.prepend(lens);const glass=null;let tween;
const update=(instant=false)=>{const button=root.querySelector('[aria-pressed=true],[aria-selected=true]');if(!button)return;const left=button.offsetLeft,width=button.offsetWidth;if(tween)tween.kill();if(reduced()||instant){gsap.set(lens,{x:left,width});}else{tween=gsap.to(lens,{x:left,width,duration:.4,ease:'power3.out',overwrite:true});}};
new MutationObserver(()=>update()).observe(root,{attributes:true,attributeFilter:['aria-pressed','aria-selected'],subtree:true});new ResizeObserver(()=>update(true)).observe(root);update(true);groups.push({root,lens,update,glass});}
// The touch response changes elevation; it does not replace the control's existing transform.
const held=new Map(),pressedTools=new Set();let presses=0;function eligible(e){return e?.closest('button,a')?.matches('button:not(:disabled),a[href]')?e.closest('button,a'):null;}
function release(button){const tween=held.get(button);if(tween)tween.kill();held.delete(button);if(reduced()){gsap.set(button,{'--press-scale':1});return;}gsap.to(button,{'--press-scale':1,duration:.42,ease:'back.out(2)',overwrite:'auto',onComplete:()=>button.style.removeProperty('--press-scale')});}
document.addEventListener('pointerdown',e=>{if(e.button!==0||reduced())return;const button=eligible(e.target);if(!button)return;button.classList.add('press-tool');pressedTools.add(button);held.set(button,gsap.to(button,{'--press-scale':.96,duration:.1,ease:'power2.out',overwrite:'auto'}));},{passive:true});
for(const event of ['pointerup','pointercancel'])document.addEventListener(event,()=>[...held.keys()].forEach(release),{passive:true});
document.addEventListener('click',e=>{const button=eligible(e.target);if(!button||reduced())return;presses++;if(e.detail===0){button.classList.add('press-tool');pressedTools.add(button);held.set(button,gsap.to(button,{'--press-scale':.96,duration:.08,onComplete:()=>release(button)}));}
if(button.matches('[data-context]')){document.querySelectorAll('.context-receipt').forEach(el=>{gsap.fromTo(el,{boxShadow:'inset 0 0 0 1px #ffffffef'},{boxShadow:'inset 0 0 0 1px #ffffff00',duration:.6,overwrite:true});});}
if(button.matches('.audio-play,[data-plyr=play],[data-sound-chapter]')){gsap.fromTo(document.querySelector('.record-art'),{boxShadow:'inset 0 1px 0 #ffffffd0,0 0 0 3px #b4d5e740'},{boxShadow:'inset 0 1px 0 #d1eafca0,0 8px 18px #294a631a',duration:.5,overwrite:true});}
});
function reduceTools(){if(reduced()){for(const b of pressedTools){gsap.killTweensOf(b,'--press-scale');b.style.removeProperty('--press-scale');}held.clear();document.querySelectorAll('.touch-impression').forEach(el=>{gsap.killTweensOf(el);el.remove();});gsap.killTweensOf(document.querySelector('.inspector-panel'));gsap.set(document.querySelector('.inspector-panel'),{rotationX:0,y:0});}groups.forEach(g=>g.update(true));}document.querySelector('.reduce').addEventListener('click',reduceTools);mq.addEventListener('change',reduceTools);window.addEventListener('blur',()=>[...held.keys()].forEach(release));
transparency.addEventListener('change',()=>{if(transparency.matches){optical.forEach(g=>g.destroy());optical.length=0;}});
const extraSwatches=[['#C7E4DF','学习','Learning'],['#DCDFF1','研究','Research'],['#91B8CB','玻璃','Glass'],['#E6D8BC','待补','Pending']];const swatches=document.querySelector('.swatch-stack');for(const [color,zh,en] of extraSwatches){const b=document.createElement('button');b.dataset.copy=color;b.style.setProperty('--swatch',color);b.dataset.zh=zh;b.dataset.en=en;b.textContent=tr(zh,en);b.setAttribute('aria-label',tr('复制色值','Copy colour')+' '+color);b.onclick=async()=>{try{await navigator.clipboard.writeText(color);document.querySelector('.copy-status').textContent=tr('已复制 ','Copied ')+color;}catch{document.querySelector('.copy-status').textContent=color;}};swatches.append(b);}
window.paperMaterial={stats:()=>({optical:optical.length,active:optical.filter(g=>g.isActive).length,presses,groups:groups.map(g=>({left:gsap.getProperty(g.lens,'x'),width:g.lens.offsetWidth}))})};
})();
// Reference measurements are documented separately; no DeepSeek code or branded art is distributed.
(()=>{
const fine=matchMedia('(hover:hover) and (pointer:fine)'),transparency=matchMedia('(prefers-reduced-transparency:reduce)');
const sky=document.createElement('div');sky.className='ambient-sky';sky.setAttribute('aria-hidden','true');sky.innerHTML='<span class="sky-blue"></span><span class="sky-pearl"></span><span class="sky-iris"></span>';look.prepend(sky);
const field=document.createElement('div');field.className='page-light';field.setAttribute('aria-hidden','true');field.innerHTML='<span class="field-sea"></span><span class="field-iris"></span>';document.body.prepend(field);
const layers=[...sky.children,...field.children],moves=layers.map(el=>({el,x:gsap.quickTo(el,'x',{duration:.85,ease:'power3.out'}),y:gsap.quickTo(el,'y',{duration:.85,ease:'power3.out'})}));
let pointerUpdates=0;const enabled=()=>fine.matches&&!reduced()&&!transparency.matches&&!document.hidden&&!look.classList.contains('open')&&!explore.open&&!window.paperGalleryOpen;
document.addEventListener('pointermove',e=>{if(!enabled()||e.pointerType==='touch'||getComputedStyle(sky).display==='none')return;pointerUpdates++;const x=e.clientX/innerWidth-.5,y=e.clientY/innerHeight-.5;moves.forEach((m,i)=>{const depth=i<3?[35,-20,25][i]:[18,-15][i-3];m.x(x*depth);m.y(y*depth*.65);});},{passive:true});
function resetLight(){moves.forEach(m=>{m.x.tween.pause();m.y.tween.pause();gsap.set(m.el,{x:0,y:0});});}mq.addEventListener('change',resetLight);fine.addEventListener('change',resetLight);document.querySelector('.reduce').addEventListener('click',resetLight);document.addEventListener('visibilitychange',()=>{if(document.hidden)resetLight();});
const home=document.createElement('button');home.className='map-home';home.textContent='Yunmin.';home.setAttribute('aria-label',tr('回到首页','Back to home'));home.onclick=()=>goChapter(0);document.querySelector('.section-map').prepend(home);
// Reuse Tippy + Popper for cursor following, viewport constraints and keyboard-focus tooltips.
const hints=[['.work-art-open','打开作品','Open work'],['.video-preview','播放试样','Play study'],['.photo-print','看大图','Enlarge photo'],['.design-preview','展开试验','Open experiment'],['.paper-object','纹理与来源','Texture & source'],['.graphic-object','打开图形','Open graphic'],['.work-context-action','关联到工作台','Connect to desk'],['.context-receipt','回到工作台','Return to desk']];
const tips=[];for(const [selector,zh,en] of hints){document.querySelectorAll(selector).forEach(el=>{const tip=tippy(el,{content:()=>tr(zh,en),theme:'paper',arrow:false,placement:'top',followCursor:true,offset:[0,12],delay:[70,0],duration:reduced()?[0,0]:[180,120],animation:'shift-away',touch:false,trigger:'mouseenter focus',hideOnClick:true,maxWidth:220,zIndex:40,onShow:instance=>{instance.setContent(tr(zh,en));return fine.matches&&!window.paperGalleryOpen&&!explore.open&&!look.classList.contains('open');}});tips.push(tip);});}
// Light moves within a mount; the photographic layout itself remains stable.
const surfaces=[...document.querySelectorAll('.work-image,.design-art,.paper-sample')];let hovered=0;
surfaces.forEach(el=>{el.addEventListener('pointermove',e=>{if(!enabled()||e.pointerType==='touch')return;el.classList.add('surface-hover');hovered++;});el.addEventListener('pointerleave',()=>el.classList.remove('surface-hover'));});
function resetHover(){tips.forEach(t=>{t.hide();t.setProps({duration:reduced()?[0,0]:[180,120]});});surfaces.forEach(el=>{gsap.killTweensOf(el);gsap.set(el,{rotationX:0,rotationY:0});el.classList.remove('surface-hover','lit-surface');});}document.querySelector('.reduce').addEventListener('click',resetHover);mq.addEventListener('change',resetHover);fine.addEventListener('change',resetHover);window.addEventListener('blur',()=>{resetLight();resetHover();});
window.paperAtmosphere={stats:()=>({enabled:enabled(),pointerUpdates,hovered,tips:tips.length,poses:layers.map(el=>({x:gsap.getProperty(el,'x'),y:gsap.getProperty(el,'y')}))})};
})();
