const explore=document.querySelector('.explore-dialog'),exploreBody=document.querySelector('.explore-body');let learningPage=0,designTopic='type',photoPage=0,exploreState='';const tr=(a,b)=>lang==='zh'?a:b;
const photos=['photo-city','photo-ocean','photo-forest'],photoNames=[['沿着水面','Along the water'],['走到海边','At the coast'],['经过树林','Through the trees']];
const learningPages=[['排版的留白','Space in typography','练习页：字、图和间距，怎样互相让出空间。','Study page: how type, pictures, and gaps share space.'],['观察纸的表面','Looking at paper','练习页：纹理的强弱，怎样影响文字与图像。','Study page: how texture changes the reading of type and pictures.'],['一张纸的移动','A moving sheet','练习页：前后关系、速度和停下来的位置。','Study page: depth, speed, and where a movement settles.']];
function updateLearning(animatePage=true){const d=learningPages[learningPage];document.querySelector('.page-number').textContent=String(learningPage+1).padStart(2,'0')+' / 03';document.querySelector('.learning-title').textContent=tr(d[0],d[1]);document.querySelector('.learning-summary').textContent=tr(d[2],d[3]);}
document.querySelector('.learning-prev').onclick=()=>{learningPage=(learningPage+2)%3;updateLearning();};document.querySelector('.learning-next').onclick=()=>{learningPage=(learningPage+1)%3;updateLearning();};
let designDemo=null;const topics={type:['两级字形关系','Two levels of typography'],color:['蓝与纸面的关系','Blue and paper'],motion:['切换与展开是两件事','Switching and opening are separate']};function updateDesign(runDemo=false){const art=document.querySelector('.design-art');designDemo?.stop();designDemo=null;art.className='design-art material-light '+(designTopic==='type'?'type-art':designTopic==='color'?'color-art':'motion-art');art.innerHTML=designTopic==='type'?'<span>Aa</span><span>字</span><i>44 / 16</i>':designTopic==='color'?'<span></span><span></span><span></span>':'<span></span><span></span><i>0.8s</i>';document.querySelector('.design-title').textContent=tr(...topics[designTopic]);document.querySelectorAll('[data-design]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.design===designTopic)));if(runDemo&&designTopic==='motion'&&!reduced())designDemo=Motion.animate(art.firstElementChild,{transform:['translateX(0) rotate(-8deg)','translateX(45px) rotate(0deg)','translateX(0) rotate(-8deg)']},{duration:1.4,ease:'easeInOut'});}
document.querySelectorAll('[data-design]').forEach(b=>b.onclick=()=>{designTopic=b.dataset.design;updateDesign(true);});document.querySelectorAll('[data-project-type]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-project-type]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));document.querySelectorAll('.project-entry').forEach(x=>x.hidden=b.dataset.projectType!=='all'&&x.dataset.kind!==b.dataset.projectType);});document.querySelectorAll('[data-asset-filter]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-asset-filter]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));document.querySelectorAll('[data-asset-type]').forEach(x=>x.hidden=b.dataset.assetFilter!=='all'&&x.dataset.assetType!==b.dataset.assetFilter);});
document.querySelectorAll('[data-copy]').forEach(b=>b.onclick=async()=>{try{await navigator.clipboard.writeText(b.dataset.copy);document.querySelector('.copy-status').textContent=tr('已复制 ','Copied ')+b.dataset.copy;}catch{const area=document.createElement('textarea');area.value=b.dataset.copy;document.body.append(area);area.select();const ok=document.execCommand('copy');area.remove();document.querySelector('.copy-status').textContent=ok?tr('已复制 ','Copied ')+b.dataset.copy:b.dataset.copy;}});
function paperUrl(){return getComputedStyle(document.documentElement).getPropertyValue('--paper').trim().replace(/^url\(["']?|["']?\)$/g,'');}
const bookmark='<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 120 150"><path d="M30 15h60v115l-30-21-30 21z" fill="#5c7b8b"/><path d="M30 15h60L30 55z" fill="#a4bdb4"/><path d="M30 55 90 15" stroke="#ffffff88"/><circle cx="60" cy="37" r="3" fill="#fafbf8"/></svg>';
function download(data,type,name){const url=URL.createObjectURL(new Blob([data],{type})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);}
function showPhoto(i){photoPage=(i+3)%3;exploreState='photo';exploreBody.innerHTML='<h2>'+esc(tr(...photoNames[photoPage]))+'</h2><div role="img" aria-label="'+esc(tr(...photoNames[photoPage]))+'" class="atlas-photo '+photos[photoPage]+'"></div><div class="gallery-controls"><button class="gallery-prev" aria-label="上一张">←</button><span>'+String(photoPage+1).padStart(2,'0')+' / 03</span><button class="gallery-next" aria-label="下一张">→</button></div><p>'+tr('Poly Haven 公开纸卡图像 / CC0；非个人摄影。','Public postcard image from Poly Haven / CC0; not personal photography.')+'</p>';exploreBody.querySelector('.gallery-prev').onclick=()=>showPhoto(photoPage-1);exploreBody.querySelector('.gallery-next').onclick=()=>showPhoto(photoPage+1);if(!explore.open)explore.showModal();}
function openExplore(key){exploreState=key;const messages={
'project-type':['字体与构图试样','Typography & composition study','记录试样：这一轮从正式衬线标题改为较轻松的字形，并缩小标题。作品和文章的小字形式被保留。','Process study: display typography was relaxed and reduced; smaller reading text was preserved.'],
'project-home':['首页内容扩展','Expanding the homepage','记录试样：作品详情、文章正文、前后翻阅与图片放大来自现有项目功能。新增板块使用明确标注的演示内容。','Process study: existing project details, writing, pagination, and image viewing are retained. New sections use labeled demonstration content.'],
'project-reflect':['让九个部分各有形状','Nine sections, nine forms','复盘展示试样：照片需要看大图，播客需要播放与本期笔记；过程册按项目组织，学习按笔记页组织。页面不再只留下板块名字。此文字为本轮设计说明，不是本人已发布的反思。','Reflection display study: photos need a viewer; podcasts need playback and show notes. Process and learning use distinct forms. This is a design explanation, not a published personal reflection.'],
'repo':['这个个人网站','This personal website','现有公开项目：Astro 静态站，作品与文章用 Markdown，中英文分别维护。当前已接入正式页面；各区的完整页面可以独立阅读与更新。','Existing project: an Astro static site using Markdown works and posts with separate language versions. The approved design is integrated, with independently readable pages for each content section.'],
'practice':['练习项目位','Practice slot','这里先演示练习项目的介绍形式。尚无公开仓库绑定，因此不制造假链接；之后可填写背景、技术和仓库地址。','This demonstrates an exercise description. No public repository is attached; background, stack, and a real link can be added later.']};
let title='',body='';if(messages[key]){const d=messages[key];title=tr(d[0],d[1]);body='<p>'+esc(tr(d[2],d[3]))+'</p>';if(key==='repo')body+='<a href="https://github.com/yunmin311/yunmin311.github.io" target="_blank" rel="noopener">GitHub ↗</a>';}
else if(key==='album'){title=tr('公共纸卡影集','Public postcard album');body='<p>'+tr('3 张 CC0 素材试样 / 时间、地点待补；不是个人相册。','3 CC0 study images / Date and location pending; not a personal album.')+'</p><div class="album-grid">'+photos.map((cls,i)=>'<button data-album-photo="'+i+'"><span class="atlas-photo '+cls+'"></span><span>'+esc(tr(...photoNames[i]))+'</span></button>').join('')+'</div><a href="https://polyhaven.com/a/postcard_set_01" target="_blank" rel="noopener">Poly Haven / CC0 ↗</a>';}
else if(key==='podcast'){title=tr('还未命名的一期','An untitled episode');body='<p>'+tr('声音与笔记的展示试样。没有真实节目与外部平台链接。首页可试听 24 秒合成声音，测试播放、暂停与拖动。','Sound and show-notes study. No real episode or platform link is available. The homepage has 24 seconds of synthesized audio to test playback and seeking.')+'</p><p>00:00 — '+tr('淡入','Fade in')+'<br>00:08 — '+tr('音色交叠','Layered tones')+'<br>00:16 — '+tr('渐弱至结束','Fade out')+'</p>';}
else if(key==='learning'){const d=learningPages[learningPage];title=tr(d[0],d[1]);body='<p>'+esc(tr(d[2],d[3]))+'</p><p>'+tr('这是一页示例，不代表本人已经写过的学习笔记。真实内容可补上日期、来源与正文；现在可以先翻看三种展示。','This is a demonstration page, not an existing personal learning note. Date, sources, and body text can be added with real content.')+'</p>';}
else if(key==='design'){title=tr(...topics[designTopic]);const d=designTopic==='type'?['本页的实际字号：桌面 76 / 16，手机 54 / 15。示例使用较轻松的展示字与文楷小字。','Actual sizes on this page: desktop 76 / 16, mobile 54 / 15.']:designTopic==='color'?['本页配色试样：蓝 #D0E3EB、灰绿 #DCE4DB、灰紫 #E3DEE8、暖纸 #F0ECE2。点击素材库中的色卡可以复制。','Palette study: blue #D0E3EB, sage #DCE4DB, violet #E3DEE8, warm paper #F0ECE2. Copy these in Assets.']:['纸卡切换只改变最前一张；点击才展开阅读纸页。这样浏览图像不需要反复打开页面。','Changing the front card is separate from opening its reading sheet, so browsing does not repeatedly open content.'];body='<p>'+tr(...d)+'</p><p>'+tr('这是本轮设计实验的说明，尚未整理成正式研究文章。','This explains the current design experiment; it is not a published research article.')+'</p>';}
else if(key==='sand-blue'||key==='sand-sage'){title=key==='sand-blue'?tr('蓝色纹理','Blue pigment'):tr('灰绿纹理','Sage pigment');const original=window.PAPER_GENERATED_ASSETS[key],preview=window.paperMaterialPreview?.[key]||original;body='<div class="sand-preview" style="background-image:url('+preview+')"></div><p>'+tr('生成素材试样，不是个人作品。','AI generated texture study, not an existing personal work.')+'</p><div class="download-links"><a download="'+key+'.png" href="'+original+'">'+tr('下载原图','Download original')+'</a></div>';}
else if(key==='paper'){title='Paper 001';body='<div class="paper-sample" style="height:190px;transform:none"></div><p>'+tr('ambientCG 的原纸张纹理，CC0。可以下载这张试样与完整许可；非个人原创素材。','Original paper texture from ambientCG, CC0. Download the sample and full license; not a personal original asset.')+'</p><div class="download-links"><a download="Paper001-Color.jpg" href="'+paperUrl()+'">'+tr('下载纸张','Download paper')+'</a><button data-license-download>'+tr('下载 CC0 许可','Download CC0 license')+'</button><a href="https://ambientcg.com/a/Paper001" target="_blank" rel="noopener">'+tr('查看来源 ↗','Source ↗')+'</a></div>';}
else if(key==='graphic'){title=tr('折纸书签','Folded bookmark');body='<div class="bookmark-art">'+bookmark+'</div><p>'+tr('本轮生成的原创 SVG 图形试样，不代表已有个人作品。此图形以 CC0 提供，可复制、修改与使用。','An original SVG graphic generated for this study, not an existing personal work. The graphic is offered under CC0 for copying, modification, and use.')+'</p><div class="download-links"><button data-graphic-download>'+tr('下载 SVG','Download SVG')+'</button><button data-license-download>'+tr('下载 CC0 许可','Download CC0 license')+'</button></div>';}
exploreBody.innerHTML='<h2>'+esc(title)+'</h2>'+body;exploreBody.querySelectorAll('[data-album-photo]').forEach(b=>b.onclick=()=>showPhoto(+b.dataset.albumPhoto));exploreBody.querySelector('[data-graphic-download]')?.addEventListener('click',()=>download(bookmark,'image/svg+xml','folded-bookmark.svg'));exploreBody.querySelector('[data-license-download]')?.addEventListener('click',()=>{const licenses=JSON.parse(document.querySelector('#licenses').textContent),license=licenses['Paper001-CC0-LICENSE.txt'];download(key==='graphic'?'Folded bookmark graphic study, 2026-10-01. Dedicated to CC0.\n\n'+license:license,'text/plain','CC0-LICENSE.txt');});explore.showModal();}
document.querySelectorAll('[data-explore]').forEach(b=>b.onclick=()=>openExplore(b.dataset.explore));document.querySelectorAll('[data-photo]').forEach(b=>b.onclick=()=>showPhoto(+b.dataset.photo));document.querySelector('.explore-close').onclick=()=>explore.close();explore.addEventListener('keydown',e=>{if(exploreState==='photo'&&(e.key==='ArrowRight'||e.key==='ArrowLeft')){e.preventDefault();showPhoto(photoPage+(e.key==='ArrowRight'?1:-1));}});
const originalLanguage=document.querySelector('.language').onclick;document.querySelector('.language').onclick=()=>{originalLanguage();updateLearning(false);updateDesign();updateAudioLabel();};
document.querySelectorAll('[data-front]').forEach(b=>b.onclick=()=>window.setFrontPaper?.(+b.dataset.front));const frontObserver=new MutationObserver(()=>{const front=document.querySelector('.stage').dataset.front;document.querySelectorAll('[data-front]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.front===front)));});frontObserver.observe(document.querySelector('.stage'),{attributes:true,attributeFilter:['data-front']});
let audioPlaying=false,recordMotion=null;const audio=document.querySelector('#podcast-audio'),audioButton=document.querySelector('.audio-play'),seek=document.querySelector('.audio-seek'),time=document.querySelector('.audio-time');
function updateAudioLabel(){audioButton.textContent=audioPlaying?tr('暂停','Pause'):tr('试听','Listen');audioButton.setAttribute('aria-pressed',String(audioPlaying));}
function stopAudio(){audio.pause();}async function playAudio(){try{await audio.play();}catch(error){console.warn('Music study unavailable:',error);}}audioButton.onclick=()=>audio.paused?playAudio():stopAudio();seek.oninput=()=>audio.currentTime=+seek.value;
let recordPhase=0,recordStarted=0;const record=document.querySelector('.vinyl');
function resumeRecord(){if(reduced()||recordMotion)return;recordStarted=performance.now();recordMotion=record.animate([{transform:'rotate('+recordPhase+'deg)'},{transform:'rotate('+(recordPhase+360)+'deg)'}],{duration:8000,iterations:Infinity,easing:'linear'});}
function pauseRecord(){if(!recordMotion)return;const matrix=new DOMMatrix(getComputedStyle(record).transform);recordPhase=(Math.atan2(matrix.b,matrix.a)*180/Math.PI+360)%360;recordMotion.cancel();recordMotion=null;record.style.transform='rotate('+recordPhase+'deg)';}
audio.addEventListener('play',()=>{audioPlaying=true;updateAudioLabel();resumeRecord();});audio.addEventListener('pause',()=>{audioPlaying=false;pauseRecord();updateAudioLabel();});audio.addEventListener('ended',()=>{audioPlaying=false;pauseRecord();updateAudioLabel();});
function audioTick(){seek.value=audio.currentTime;time.textContent='00:'+String(Math.floor(audio.currentTime)).padStart(2,'0');if(reduced()&&recordMotion){pauseRecord();}requestAnimationFrame(audioTick);}audioTick();
