// The hero header stays in the document. The chapter rail owns the sticky spring.
(()=>{
const nav=document.querySelector('.nav'),wrapper=document.createElement('header');wrapper.className='header-wrap';wrapper.setAttribute('aria-label',tr('主导航','Main navigation'));document.body.append(wrapper);wrapper.append(nav);
const skip=document.createElement('a');skip.className='skip-main';skip.href='#works';skip.dataset.zh='跳到内容';skip.dataset.en='Skip to content';skip.textContent=tr(skip.dataset.zh,skip.dataset.en);document.body.prepend(skip);
const rail=document.querySelector('.section-map'),dock=document.createElement('div'),sentinel=document.createElement('i');dock.className='chapter-dock';sentinel.className='chapter-sentinel';sentinel.setAttribute('aria-hidden','true');rail.before(sentinel,dock);dock.append(rail);
const lens=document.createElement('i');lens.className='chapter-lens';lens.setAttribute('aria-hidden','true');rail.prepend(lens);let lensTween=null,animation=null,docked=null,compactWidth=739,raf=0,epoch=0;
function marker(instant=false){lensTween?.kill();const selected=rail.querySelector('a[aria-current=location]');if(!selected){gsap.set(lens,{opacity:0});return;}const vars={x:selected.offsetLeft,width:selected.offsetWidth,opacity:1};if(instant||reduced())gsap.set(lens,vars);else lensTween=gsap.to(lens,{...vars,duration:.48,ease:'power3.out',overwrite:true});}
function measure(){const probe=rail.cloneNode(true);probe.removeAttribute('aria-label');probe.querySelectorAll('i').forEach(el=>el.remove());probe.style.cssText='position:absolute!important;visibility:hidden!important;pointer-events:none!important;width:max-content!important;max-width:none!important;backdrop-filter:none!important;inset:0 auto auto 0!important;';probe.querySelectorAll('a').forEach(el=>{el.style.flex='0 0 auto';el.style.width='max-content';});dock.append(probe);compactWidth=Math.ceil(probe.getBoundingClientRect().width);probe.remove();wrapper.style.top=(document.querySelector('.review').offsetHeight+(innerWidth<560?12:16))+'px';window.paperGlassTop?.update({width:nav.offsetWidth,height:nav.offsetHeight,borderRadius:28});}
function morph(force=false){const top=innerWidth<560?12:16,next=sentinel.getBoundingClientRect().top+22<=top+.5;if(next===docked&&!force)return;docked=next;dock.classList.toggle('is-docked',next);rail.classList.toggle('is-docked',next);animation?.stop();const target=Math.min(dock.clientWidth,next?dock.clientWidth:compactWidth),token=++epoch;animation=Motion.animate(rail,{width:target},reduced()?{duration:0}:{type:'spring',stiffness:180,damping:28});animation.then(()=>{if(token!==epoch)return;marker(true);window.paperGlassRail?.update({width:rail.offsetWidth,height:rail.offsetHeight,borderRadius:28});}).catch(()=>{});}
function schedule(){if(raf)return;raf=requestAnimationFrame(()=>{raf=0;morph();});}window.addEventListener('scroll',schedule,{passive:true});window.addEventListener('resize',()=>{measure();morph(true);});document.fonts.ready.then(()=>{measure();morph(true);});
new MutationObserver(()=>marker()).observe(rail,{attributes:true,subtree:true,attributeFilter:['aria-current']});new MutationObserver(()=>{measure();morph(true);}).observe(document.documentElement,{attributes:true,attributeFilter:['lang']});new ResizeObserver(()=>marker(true)).observe(rail);
const settle=()=>{morph(true);marker(true);};mq.addEventListener('change',settle);document.querySelector('.reduce').addEventListener('click',settle);measure();morph(true);
if(!matchMedia('(prefers-reduced-transparency:reduce)').matches&&!matchMedia('(forced-colors:active)').matches){const optic=document.createElement('i');optic.className='glass-optic';optic.setAttribute('aria-hidden','true');rail.prepend(optic);window.paperGlassRail=PaperGlass.createLiquidGlass(optic,{borderRadius:28,width:rail.offsetWidth,height:rail.offsetHeight,scale:-12,aberration:[0,.15,.3],border:.06,blur:4,displaceBlur:2,saturation:1.04,fallbackFilter:'blur(18px)'});}
window.paperNavigation={stats:()=>({docked,headerTop:wrapper.getBoundingClientRect().top,headerWidth:nav.offsetWidth,railTop:dock.getBoundingClientRect().top,railWidth:rail.getBoundingClientRect().width,compactWidth,railOverflow:rail.scrollWidth-rail.clientWidth,spring:{stiffness:180,damping:28}})};
})();
// One owner per animated plate. Never animate the section's layout rectangle.
(()=>{
const pending=new Map();let turns=0;function turn(el,axis='y'){if(!el||reduced())return;turns++;pending.get(el)?.kill();el.classList.add('plate-turn');gsap.killTweensOf(el,'rotationX,rotationY,y');let t;t=gsap.fromTo(el,{rotationX:axis==='x'?4:0,rotationY:axis==='y'?-6:0,y:3,transformPerspective:900},{rotationX:0,rotationY:0,y:0,duration:.5,ease:'power3.out',overwrite:'auto',onComplete:()=>{if(pending.get(el)!==t)return;pending.delete(el);gsap.set(el,{clearProps:'transform,transformOrigin,willChange'});el.classList.remove('plate-turn');}});pending.set(el,t);}
for(const [selectors,target] of [['[data-design]','.design-art'],['[data-note-page],.learning-next,.learning-prev','#learning-panel'],['[data-bench-view],[data-context]','.inspector-panel']]){document.addEventListener('click',e=>{if(e.target.closest(selectors))turn(document.querySelector(target));});}
const previousExplore=openExplore;openExplore=function(key){previousExplore(key);turn(exploreBody,'x');};
// Filter feedback uses clip/opacity on the new content. It cannot shift an existing row.
let filterTurns=0;const filterAnimations=new Map();document.addEventListener('click',e=>{const button=e.target.closest('[data-work-filter],[data-work-view],[data-project-type],[data-asset-filter],[data-repo-filter],[data-reading-view]');if(!button||reduced())return;filterTurns++;const root=button.closest('.works-section,.projects-section,.assets-section,.repos-section,.writing-section');if(!root)return;const nodes=[...root.querySelectorAll('.work-card,.project-entry,.asset-object,.repo-folder,.writing-list button')].filter(el=>!el.hidden);nodes.forEach((el,i)=>{filterAnimations.get(el)?.cancel();const a=el.animate([{opacity:.5,clipPath:'inset(0 0 7% 0 round 5px)'},{opacity:1,clipPath:'inset(0 0 0 0 round 5px)'}],{duration:320,delay:i*30,easing:'cubic-bezier(.2,0,0,1)'});filterAnimations.set(el,a);a.finished.then(()=>{if(filterAnimations.get(el)===a)filterAnimations.delete(el);}).catch(()=>{});});});
function settle(){if(!reduced())return;pending.forEach((t,el)=>{t.kill();gsap.set(el,{clearProps:'transform,transformOrigin,willChange'});el.classList.remove('plate-turn');});pending.clear();filterAnimations.forEach(a=>a.cancel());filterAnimations.clear();designDemo?.stop();designDemo=null;stopLens();gsap.set(navLens,{opacity:0});}document.querySelector('.reduce').addEventListener('click',settle);mq.addEventListener('change',settle);window.addEventListener('pagehide',settle);
window.paperLeaf={stats:()=>({turns,filterTurns,active:pending.size,filters:filterAnimations.size})};
})();
// Canvas Confetti's actual physics, bounded to one short blue/pearl print burst per press.
(()=>{
const canvas=document.createElement('canvas');canvas.className='click-particles';canvas.setAttribute('aria-hidden','true');canvas.tabIndex=-1;canvas.setAttribute('popover','manual');document.body.append(canvas);const burst=confetti.create(canvas,{resize:true,useWorker:false});let count=0,active=false,timer=0;
function show(x,y,strong=true){if(reduced()||document.hidden)return;if(canvas.showPopover){if(canvas.matches(':popover-open'))canvas.hidePopover();canvas.showPopover();}active=true;count++;clearTimeout(timer);burst({particleCount:strong?26:16,startVelocity:strong?11:8,spread:360,angle:90,ticks:80,gravity:.24,decay:.90,scalar:.48,drift:0,origin:{x:x/innerWidth,y:y/innerHeight},colors:['#547c9c','#8eafcc','#cedeea','#f3f8fc','#abb9d2'],shapes:['square','circle'],disableForReducedMotion:true}).then(()=>{active=false;});timer=setTimeout(stop,1350);}
document.addEventListener('pointerdown',e=>{if(e.button!==0||e.target.closest('input,textarea,[role=slider]'))return;show(e.clientX,e.clientY,!!e.target.closest('button,a'));},{capture:true,passive:true});document.addEventListener('click',e=>{if(e.detail!==0)return;const button=e.target.closest('button,a');if(!button)return;const r=button.getBoundingClientRect();if(r.width>0)show(r.left+r.width/2,r.top+r.height/2,true);},{capture:true});
function stop(){clearTimeout(timer);burst.reset();active=false;if(canvas.matches(':popover-open'))canvas.hidePopover();}mq.addEventListener('change',()=>{if(reduced())stop();});document.querySelector('.reduce').addEventListener('click',()=>{if(reduced())stop();});window.addEventListener('blur',stop);document.addEventListener('visibilitychange',()=>{if(document.hidden)stop();});window.addEventListener('pagehide',stop);
window.paperClicks={stats:()=>({count,active,topLayer:canvas.matches(':popover-open'),reduced:reduced()}),show,stop};
})();
// Pointer movement is owned by the cloud Flowmap; the independent click burst remains.
window.paperTrail={stats:()=>({active:window.paperCloud?.stats().active||false,allowed:!reduced(),mode:'cloud-flow'}),stop:()=>window.paperCloud?.stop()};
window.paperSand={stats:()=>({coats:0})};

// At narrow widths the gutter marker stays visible but cannot cover content controls.
(()=>{const narrow=matchMedia('(max-width:1100px)'),marker=document.querySelector('.ruler-slider');function sync(){marker.tabIndex=narrow.matches?-1:0;marker.setAttribute('role',narrow.matches?'progressbar':'slider');}narrow.addEventListener('change',sync);sync();})();
