const chapterIds=['home','works','photos','podcast','projects','learning','design-notes','assets','repos','writing','about'];const chapterLabels=[['首页','Home'],['作品','Works'],['影集','Photos'],['播客','Podcast'],['项目记录','Projects'],['学习记录','Learning'],['设计整合','Design notes'],['素材库','Assets'],['代码库','Repos'],['文字','Writing'],['关于','About']];const chapterNodes=chapterIds.map(id=>document.getElementById(id));const ruler=document.querySelector('.page-ruler'),rulerSlider=document.querySelector('.ruler-slider'),rulerTicks=document.querySelector('.ruler-ticks'),rulerThumb=document.querySelector('.ruler-thumb'),rulerCaption=document.querySelector('.ruler-caption');let currentChapter=0,rulerDragging=false,pinUntil=0,scrollScheduled=false,pinTimer=null;
chapterIds.forEach((id,i)=>{const tick=document.createElement('span');tick.className='ruler-tick'+(i%2===0?' major':'');tick.style.top=(i/(chapterIds.length-1)*100)+'%';rulerTicks.append(tick);});
function syncRuler(){const h=rulerSlider.getBoundingClientRect().height,y=16+currentChapter/(chapterIds.length-1)*(h-32),label=chapterLabels[currentChapter][lang==='zh'?0:1];rulerThumb.style.transform='translateY('+(y-5)+'px)';rulerCaption.style.top=(y-18)+'px';rulerCaption.textContent=label;rulerSlider.setAttribute('aria-label',lang==='zh'?'拖动或点击切换板块':'Drag or click to change section');rulerSlider.setAttribute('aria-valuenow',String(currentChapter));rulerSlider.setAttribute('aria-valuetext',label);document.querySelector('.ruler-count').textContent=String(currentChapter).padStart(2,'0');[...rulerTicks.children].forEach((e,i)=>e.classList.toggle('current',i===currentChapter));chapterNodes.forEach((e,i)=>e.classList.toggle('is-current',i===currentChapter));document.querySelectorAll('.section-map a').forEach(a=>{if(a.getAttribute('href')==='#'+chapterIds[currentChapter])a.setAttribute('aria-current','location');else a.removeAttribute('aria-current');});}
function goChapter(i,instant=false){i=Math.max(0,Math.min(chapterIds.length-1,i));if(document.querySelector('.look').classList.contains('open'))close({restoreScroll:false,immediate:true});currentChapter=i;pinUntil=performance.now()+900;clearTimeout(pinTimer);pinTimer=setTimeout(watchScroll,950);syncRuler();const target=chapterNodes[i],top=i===0?0:target.getBoundingClientRect().top+scrollY-96;window.scrollTo({top:Math.max(0,top),behavior:instant||reduced()?'instant':'smooth'});if(instant)requestAnimationFrame(()=>window.paperPageMotion?.finishJump());}
function indexFromPointer(e){const r=rulerSlider.getBoundingClientRect();return Math.round(Math.max(0,Math.min(1,(e.clientY-r.top-16)/(r.height-32)))*(chapterIds.length-1));}
rulerSlider.addEventListener('pointerdown',e=>{if(e.button!==0)return;e.preventDefault();rulerDragging=true;ruler.classList.add('dragging');rulerSlider.focus({preventScroll:true});rulerSlider.setPointerCapture(e.pointerId);goChapter(indexFromPointer(e),true);});rulerSlider.addEventListener('pointermove',e=>{if(rulerDragging){const i=indexFromPointer(e);if(i!==currentChapter)goChapter(i,true);}});function finishRuler(){rulerDragging=false;ruler.classList.remove('dragging');pinUntil=performance.now()+300;}rulerSlider.addEventListener('pointerup',finishRuler);rulerSlider.addEventListener('pointercancel',finishRuler);rulerSlider.addEventListener('lostpointercapture',finishRuler);
rulerSlider.addEventListener('keydown',e=>{const step=e.key==='ArrowDown'||e.key==='ArrowRight'||e.key==='PageDown'?1:e.key==='ArrowUp'||e.key==='ArrowLeft'||e.key==='PageUp'?-1:0;if(step||e.key==='Home'||e.key==='End'){e.preventDefault();goChapter(e.key==='Home'?0:e.key==='End'?chapterIds.length-1:currentChapter+step);}});
function watchScroll(){if(scrollScheduled)return;scrollScheduled=true;requestAnimationFrame(()=>{scrollScheduled=false;if(rulerDragging||performance.now()<pinUntil)return;const max=document.documentElement.scrollHeight-innerHeight;if(scrollY<80)currentChapter=0;else if(scrollY>=max-3)currentChapter=chapterIds.length-1;else{let best=currentChapter,bestDistance=Infinity;chapterNodes.forEach((node,i)=>{const d=Math.abs(node.getBoundingClientRect().top-96);if(d<bestDistance-1||(Math.abs(d-bestDistance)<=1&&i===currentChapter)){best=i;bestDistance=d;}});currentChapter=best;}syncRuler();});}
window.addEventListener('scroll',watchScroll,{passive:true});new ResizeObserver(()=>{syncRuler();watchScroll();}).observe(document.body);
document.querySelectorAll('a[href^="#"]').forEach(a=>{const id=a.getAttribute('href').slice(1),i=chapterIds.indexOf(id);if(i<0)return;a.addEventListener('click',e=>{e.preventDefault();goChapter(i);history.replaceState(null,'','#'+id);});a.addEventListener('pointerenter',()=>chapterNodes[i].classList.add('related-preview'));a.addEventListener('pointerleave',()=>chapterNodes[i].classList.remove('related-preview'));});
document.addEventListener('focusin',e=>{if(e.target.closest('.page-ruler'))return;const i=chapterNodes.findIndex(el=>el.contains(e.target));if(i>=0){currentChapter=i;pinUntil=performance.now()+350;syncRuler();}});
const rulerLanguageHandler=document.querySelector('.language').onclick;document.querySelector('.language').onclick=()=>{rulerLanguageHandler();syncRuler();};syncRuler();watchScroll();
