import {mountCloudCanvas} from './cloud-canvas.js';
import './vendor/confetti.js';
import './scroll-controls.js';
const reduce=matchMedia('(prefers-reduced-motion:reduce)'),button=document.querySelector('.reduce');
button.addEventListener('click',()=>{document.body.classList.toggle('motion-off');button.setAttribute('aria-pressed',String(document.body.classList.contains('motion-off')));});
(async()=>{try{const response=await fetch('/assets/paper/material-cache.json');if(!response.ok)return;const cached=await response.json(),sky=document.querySelector('.cloud-sky');sky.style.backgroundImage='url("'+cached.processed['cloud-01']+'")';document.documentElement.style.setProperty('--reading-sand','url("'+(cached.surfaceTiles?.['sand-blue']||cached.processed['sand-blue'])+'")');const flow=await mountCloudCanvas(sky,['cloud-01','cloud-02','cloud-03'].map(k=>cached.processed[k]));window.paperCloud=flow;}catch(e){console.warn('Cloud background unavailable',e.message);}})();
const canvas=document.createElement('canvas');canvas.className='click-particles';canvas.setAttribute('aria-hidden','true');canvas.setAttribute('popover','manual');document.body.append(canvas);const burst=window.confetti.create(canvas,{resize:true,useWorker:false});let count=0,active=false,timer=0;
function stop(){clearTimeout(timer);burst.reset();active=false;if(canvas.matches(':popover-open'))canvas.hidePopover();}
function show(x,y){if(reduce.matches||document.body.classList.contains('motion-off'))return;if(canvas.matches(':popover-open'))canvas.hidePopover();canvas.showPopover();active=true;count++;burst({particleCount:20,startVelocity:9,spread:360,ticks:80,gravity:.24,decay:.90,scalar:.48,origin:{x:x/innerWidth,y:y/innerHeight},colors:['#547c9c','#8eafcc','#cedeea','#f3f8fc','#abb9d2'],disableForReducedMotion:true}).then(()=>active=false);clearTimeout(timer);timer=setTimeout(stop,1350);}
document.addEventListener('pointerdown',e=>{if(e.button!==0||e.target.closest('input,textarea,[role=slider]'))return;show(e.clientX,e.clientY);},{capture:true,passive:true});reduce.addEventListener('change',stop);button.addEventListener('click',stop);addEventListener('blur',stop);addEventListener('pagehide',stop);window.paperClicks={show,stop,stats:()=>({count,active,reduced:reduce.matches||document.body.classList.contains('motion-off')})};
for(const table of document.querySelectorAll('.post-body table,.work-body table,.note-body table')){const wrapper=document.createElement('div');wrapper.className='table-viewport';table.before(wrapper);wrapper.append(table);}
