// The existing player is moved, never cloned: one audio element, one playback state.
(()=>{
const pod=document.getElementById('podcast'),media=pod.closest('.media-spread');pod.removeAttribute('id');
const marker=document.createElement('div');marker.id='podcast';marker.className='music-inline';marker.innerHTML='<p data-zh="照片之外，也可以听一会儿。" data-en="A little listening alongside the images.">照片之外，也可以听一会儿。</p><button data-music-open data-zh="打开音乐 ↗" data-en="Open music ↗">打开音乐 ↗</button>';media.querySelector('.photo-section').append(marker);chapterNodes[3]=marker;
const panel=document.createElement('dialog');panel.className='music-panel';panel.id='music-panel';panel.setAttribute('aria-label','Music player');panel.innerHTML='<header class="music-panel-head"><h2 data-zh="音乐" data-en="Music">音乐</h2><button class="music-close" aria-label="Close music">×</button></header>';panel.append(pod);const note=document.createElement('p');note.className='music-note';note.dataset.zh='歌单待补。目前试听的是 24 秒合成声音。';note.dataset.en='Playlist pending. This is a 24-second synthesized sound study.';note.textContent=note.dataset.zh;panel.append(note);document.body.append(panel);
const toggle=document.createElement('button');toggle.className='music-toggle';toggle.setAttribute('aria-expanded','false');toggle.setAttribute('aria-controls',panel.id);toggle.innerHTML='<i class="music-mini-disc" aria-hidden="true"></i><span data-zh="音乐" data-en="Music">音乐</span><i class="music-playing-mark" aria-hidden="true"></i>';document.body.append(toggle);
const caption=pod.querySelector('.record-caption p'),sub=pod.querySelector('.record-caption small');caption.dataset.zh='声音试样';caption.dataset.en='Sound study';caption.textContent=caption.dataset.zh;sub.dataset.zh='播放与收起';sub.dataset.en='Play and fold away';sub.textContent=sub.dataset.zh;
chapterLabels[3]=['音乐','Music'];const musicLink=document.querySelector('.section-map a[href="#podcast"]');musicLink.dataset.zh='音乐';musicLink.dataset.en='Music';musicLink.textContent='音乐';musicLink.addEventListener('click',e=>{e.preventDefault();e.stopImmediatePropagation();openMusic();},{capture:true});
let motion=null,epoch=0,phase='closed',returnFocus=null;
function stop(){motion?.cancel();motion=null;}
function run(frames,ms,done){stop();const token=++epoch;if(reduced()){done?.();return;}motion=panel.animate(frames,{duration:ms,easing:'cubic-bezier(.2,0,0,1)'});motion.finished.then(()=>{if(token===epoch){motion=null;done?.();}}).catch(()=>{});}
function openMusic(){if(panel.open&&phase!=='closing'){panel.querySelector('.music-close').focus({preventScroll:true});return;}returnFocus=document.activeElement;if(!panel.open)panel.show();phase='opening';toggle.setAttribute('aria-expanded','true');run([{opacity:0,transform:'translateY(16px) scale(.97)'},{opacity:1,transform:'translateY(0) scale(1)'}],360,()=>phase='open');panel.querySelector('.music-close').focus({preventScroll:true});}
function closeMusic(focus=true){if(!panel.open)return;phase='closing';run([{opacity:1,transform:'translateY(0) scale(1)'},{opacity:0,transform:'translateY(10px) scale(.98)'}],220,()=>{panel.close();phase='closed';toggle.setAttribute('aria-expanded','false');if(focus)returnFocus?.focus({preventScroll:true});});}
toggle.onclick=()=>panel.open?closeMusic():openMusic();panel.querySelector('.music-close').onclick=()=>closeMusic();marker.querySelector('[data-music-open]').onclick=openMusic;panel.addEventListener('cancel',e=>{e.preventDefault();closeMusic();});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&panel.open&&!document.querySelector('.recovered-dialog[open]')){e.preventDefault();e.stopImmediatePropagation();closeMusic();}},{capture:true});audio.addEventListener('play',()=>toggle.classList.add('is-playing'));['pause','ended'].forEach(e=>audio.addEventListener(e,()=>toggle.classList.remove('is-playing')));
const stopForDialog=()=>{stop();++epoch;if(panel.open)panel.close();phase='closed';toggle.setAttribute('aria-expanded','false');};new MutationObserver(()=>{if(explore.open)stopForDialog();}).observe(explore,{attributes:true,attributeFilter:['open']});const priorSelect=window.onPaperSelect;window.onPaperSelect=function(i){stopForDialog();priorSelect(i);};const priorPhoto=showPhoto;showPhoto=function(i){stopForDialog();priorPhoto(i);};
const settle=()=>{if(reduced()){stop();++epoch;if(panel.open){if(phase==='closing'){panel.close();phase='closed';toggle.setAttribute('aria-expanded','false');}else phase='open';}}};mq.addEventListener('change',settle);document.querySelector('.reduce').addEventListener('click',settle);
window.paperMusic={open:openMusic,close:closeMusic,hide:stopForDialog,stats:()=>({open:panel.open,phase,playing:!audio.paused,audioElements:document.querySelectorAll('audio').length})};syncRuler();window.paperNavigation?.measure?.();
})();

// Recovered content keeps its original dates and wording. Current status is not inferred.
(()=>{
const data=window.RECOVERED_CONTENT,md=window.markdownit({html:false,linkify:false,typographer:false});const originalTableOpen=md.renderer.rules.table_open;md.renderer.rules.table_open=(...args)=>'<div class="table-viewport">'+(originalTableOpen?originalTableOpen(...args):'<table>');md.renderer.rules.table_close=()=>'</table></div>';
content.zh.posts=data.posts.map(p=>({...p}));content.en.posts=[];
const earlierMarkdown=markdown;markdown=function(text){return index===1?'<div class="recovered-article">'+md.render(text)+'</div>':earlierMarkdown(text);};const earlierFill=fill;fill=function(){earlierFill();const tag=document.querySelector('.reader-tag');tag.dataset.zh=index===1?'旧项目文章 · 2026-05':'现有内容 · 占位';tag.dataset.en=index===1?'Earlier writing · 2026-05':'Existing content · Placeholder';tag.textContent=tag.dataset[lang];if(index===1&&lang==='en')document.querySelector('.reader-note').textContent='These articles currently have Chinese drafts only. English versions are pending.';};
const links=document.createElement('div');links.className='recovered-links';links.innerHTML=[['projects','旧稿项目 ↗','Earlier projects ↗'],['blog','旧稿文章 ↗','Earlier writing ↗'],['about','旧稿介绍 ↗','Earlier about page ↗']].map(([key,zh,en])=>'<button data-recovered="'+key+'" data-zh="'+zh+'" data-en="'+en+'">'+zh+'</button>').join('');document.getElementById('projects').append(links);for(const [key,id] of [['blog','writing'],['about','about']]){const group=document.createElement('div');group.className='recovered-links';group.append(links.querySelector('[data-recovered="'+key+'"]'));document.getElementById(id).append(group);}
const dialog=document.createElement('dialog');dialog.className='recovered-dialog';dialog.setAttribute('aria-label','Recovered draft pages');dialog.innerHTML='<header class="recovered-head"><span data-zh="旧项目内容 · 2026-05 · 待确认" data-en="Earlier draft · 2026-05 · Needs review">旧项目内容 · 2026-05 · 待确认</span><button class="recovered-close" aria-label="Close recovered page">×</button></header><div class="recovered-content"></div>';document.body.append(dialog);const body=dialog.querySelector('.recovered-content');let route='projects',selected=0,focusOrigin=null,motion=null,epoch=0;
function intro(title,note){return '<h2>'+esc(title)+'</h2><p class="recovered-meta">'+esc(note)+'</p>';}
function render(){if(lang==='en'){body.innerHTML=intro('Earlier '+(route==='blog'||route==='post'?'writing':route==='about'?'about page':'projects'),'Recovered from your previous personal website.')+'<p>This material currently has a Chinese draft only. An English version has not been written.</p>';return;}
 if(route==='projects')body.innerHTML=intro('旧稿项目','原项目里的六个条目。下面的状态来自旧稿，不代表当前进度。')+'<div class="recovered-projects">'+data.projects.map((p,i)=>'<article class="recovered-item"><span class="recovered-status">旧稿标记：'+esc(p.status)+'</span><h3>'+esc(p.title)+'</h3><p>'+esc(p.desc)+'</p><div class="recovered-tags">'+p.tags.map(t=>'<span>'+esc(t)+'</span>').join('')+'</div><button data-recovered-project="'+i+'">查看详情结构 ↗</button></article>').join('')+'</div>';
 else if(route==='project'){const p=data.projects[selected];body.innerHTML='<button class="recovered-back" data-back="projects">← 返回项目</button>'+intro(p.title,'旧稿内容 · 项目详情结构试样')+'<span class="recovered-status">旧稿标记：'+esc(p.status)+'</span><h3>项目介绍</h3><p>'+esc(p.desc)+'</p><h3>使用的工具</h3><div class="recovered-tags">'+p.tags.map(t=>'<span>'+esc(t)+'</span>').join('')+'</div><div class="recovered-pending"><p>过程、图片、结果和复盘待补。旧项目还没有详情页，这里先保留完整的阅读入口。</p></div>';}
 else if(route==='blog')body.innerHTML=intro('旧稿文章','两篇已有正文，保留原来的日期与内容。')+'<div class="recovered-posts">'+data.posts.map((p,i)=>'<article class="recovered-item"><span class="recovered-meta">'+esc(p.date)+'</span><h3>'+esc(p.title)+'</h3><p>'+esc(p.summary)+'</p><button data-recovered-post="'+i+'">阅读正文 ↗</button></article>').join('')+'</div>';
 else if(route==='post'){const p=data.posts[selected];body.innerHTML='<button class="recovered-back" data-back="blog">← 返回文章</button>'+intro(p.title,p.date+' · 旧稿正文')+'<div class="recovered-article">'+md.render(p.body)+'</div>';}
 else body.innerHTML=intro('旧稿介绍','以下是原项目里的文字，先保留为草稿，等你确认。')+data.about.paragraphs.map(p=>'<p>'+esc(p)+'</p>').join('')+'<h3>兴趣领域</h3><div class="recovered-interests">'+data.about.interests.map(t=>'<span class="recovered-status">'+esc(t)+'</span>').join('')+'</div>';
 body.querySelectorAll('[data-recovered-project]').forEach(b=>b.onclick=()=>{selected=+b.dataset.recoveredProject;route='project';render();dialog.scrollTop=0;body.querySelector('.recovered-back').focus({preventScroll:true});});body.querySelectorAll('[data-recovered-post]').forEach(b=>b.onclick=()=>{selected=+b.dataset.recoveredPost;route='post';render();dialog.scrollTop=0;body.querySelector('.recovered-back').focus({preventScroll:true});});body.querySelector('[data-back]')?.addEventListener('click',e=>{route=e.currentTarget.dataset.back;render();dialog.scrollTop=0;body.querySelector('button')?.focus({preventScroll:true});});
}
function open(key,index=0){selected=index;route=key;focusOrigin=document.activeElement;window.paperMusic.hide();render();if(!dialog.open)dialog.showModal();dialog.scrollTop=0;dialog.querySelector('.recovered-close').focus({preventScroll:true});motion?.cancel();++epoch;if(!reduced())motion=dialog.animate([{opacity:0,transform:'translateY(16px) scale(.985)'},{opacity:1,transform:'translateY(0) scale(1)'}],{duration:360,easing:'cubic-bezier(.2,0,0,1)'});}
function close(){if(!dialog.open)return;motion?.cancel();const token=++epoch;const end=()=>{if(token===epoch){dialog.close();focusOrigin?.focus({preventScroll:true});}};if(reduced())end();else{motion=dialog.animate([{opacity:1,transform:'translateY(0) scale(1)'},{opacity:0,transform:'translateY(12px) scale(.985)'}],{duration:240,easing:'cubic-bezier(.2,0,0,1)'});motion.finished.then(end).catch(()=>{});}}
document.querySelectorAll('[data-recovered]').forEach(b=>b.onclick=()=>open(b.dataset.recovered));dialog.querySelector('.recovered-close').onclick=close;dialog.addEventListener('cancel',e=>{e.preventDefault();close();});const oldLanguage=document.querySelector('.language').onclick;document.querySelector('.language').onclick=()=>{oldLanguage();if(dialog.open)render();};const shelf=document.querySelector('.writing-list');shelf.innerHTML=data.posts.map((p,i)=>'<button class="zh-only" data-recovered-post="'+i+'"><span class="post-date">'+esc(p.date.replaceAll('-','.'))+'</span><span class="post-title">'+esc(p.title)+'</span><span class="post-type">旧稿正文</span><span aria-hidden="true">↗</span></button>').join('')+'<p class="en-only" hidden>These articles currently have Chinese drafts only. English versions are pending.</p>';shelf.querySelectorAll('button').forEach(b=>b.onclick=()=>open('post',+b.dataset.recoveredPost));const label=document.querySelector('.reading-tools>span');label.dataset.zh='两篇旧稿 / 点击阅读全文';label.dataset.en='Earlier writing / Chinese drafts';label.textContent=label.dataset.zh;window.paperRecovered={open,close,stats:()=>({open:dialog.open,route,projects:data.projects.length,posts:data.posts.length})};
})();
