// The existing player is moved, never cloned: one audio element, one playback state.
(()=>{
const pod=document.getElementById('podcast'),media=pod.closest('.media-spread');pod.removeAttribute('id');
const marker=document.createElement('div');marker.id='podcast';marker.className='music-inline';marker.innerHTML='<p data-zh="照片之外，也可以听一会儿。" data-en="A little listening alongside the images.">照片之外，也可以听一会儿。</p><button data-music-open data-zh="打开音乐 ↗" data-en="Open music ↗">打开音乐 ↗</button>';media.querySelector('.photo-section').append(marker);const musicChapter=chapterIds.indexOf('podcast');if(musicChapter>=0)chapterNodes[musicChapter]=marker;marker.hidden=true;
const panel=document.createElement('dialog');panel.className='music-panel';panel.id='music-panel';panel.setAttribute('aria-label','Music player');panel.innerHTML='<header class="music-panel-head"><h2 data-zh="音乐" data-en="Music">音乐</h2><button class="music-close" aria-label="Close music">×</button></header>';panel.append(pod);const note=document.createElement('p');note.className='music-note';note.dataset.zh='歌单待补。目前试听的是 24 秒合成声音。';note.dataset.en='Playlist pending. This is a 24-second synthesized sound study.';note.textContent=note.dataset.zh;panel.append(note);document.body.append(panel);
const toggle=document.createElement('button');toggle.className='music-toggle';toggle.setAttribute('aria-expanded','false');toggle.setAttribute('aria-controls',panel.id);toggle.innerHTML='<i class="music-mini-disc" aria-hidden="true"></i><span data-zh="声音试样" data-en="Sound study">声音试样</span><i class="music-playing-mark" aria-hidden="true"></i>';document.body.append(toggle);
const caption=pod.querySelector('.record-caption p'),sub=pod.querySelector('.record-caption small');caption.dataset.zh='声音试样';caption.dataset.en='Sound study';caption.textContent=caption.dataset.zh;sub.dataset.zh='播放与收起';sub.dataset.en='Play and fold away';sub.textContent=sub.dataset.zh;
if(musicChapter>=0)chapterLabels[musicChapter]=['音乐','Music'];const musicLink=document.querySelector('.section-map a[href="#podcast"]');musicLink.dataset.zh='音乐';musicLink.dataset.en='Music';musicLink.textContent='音乐';musicLink.addEventListener('click',e=>{e.preventDefault();e.stopImmediatePropagation();openMusic();},{capture:true});
let motion=null,epoch=0,phase='closed',returnFocus=null;
function stop(){motion?.cancel();motion=null;}
function run(frames,ms,done){stop();const token=++epoch;if(reduced()){done?.();return;}motion=panel.animate(frames,{duration:ms,easing:'cubic-bezier(.2,0,0,1)'});motion.finished.then(()=>{if(token===epoch){motion=null;done?.();}}).catch(()=>{});}
function openMusic(){if(panel.open&&phase!=='closing'){panel.querySelector('.music-close').focus({preventScroll:true});return;}returnFocus=document.activeElement;if(!panel.open)panel.show();phase='opening';toggle.setAttribute('aria-expanded','true');run([{opacity:0,transform:'translateY(16px) scale(.97)'},{opacity:1,transform:'translateY(0) scale(1)'}],360,()=>phase='open');panel.querySelector('.music-close').focus({preventScroll:true});}
function closeMusic(focus=true){if(!panel.open)return;phase='closing';run([{opacity:1,transform:'translateY(0) scale(1)'},{opacity:0,transform:'translateY(10px) scale(.98)'}],220,()=>{panel.close();phase='closed';toggle.setAttribute('aria-expanded','false');if(focus)returnFocus?.focus({preventScroll:true});});}
toggle.onclick=()=>panel.open?closeMusic():openMusic();panel.querySelector('.music-close').onclick=()=>closeMusic();marker.querySelector('[data-music-open]').onclick=openMusic;panel.addEventListener('cancel',e=>{e.preventDefault();closeMusic();});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&panel.open&&!document.querySelector('.recovered-dialog[open]')){e.preventDefault();e.stopImmediatePropagation();closeMusic();}},{capture:true});audio.addEventListener('play',()=>toggle.classList.add('is-playing'));['pause','ended'].forEach(e=>audio.addEventListener(e,()=>toggle.classList.remove('is-playing')));
const stopForDialog=()=>{stop();++epoch;if(panel.open)panel.close();phase='closed';toggle.setAttribute('aria-expanded','false');};new MutationObserver(()=>{if(explore.open)stopForDialog();}).observe(explore,{attributes:true,attributeFilter:['open']});const priorSelect=window.onPaperSelect;window.onPaperSelect=function(i){stopForDialog();priorSelect(i);};const priorPhoto=showPhoto;showPhoto=function(i){stopForDialog();priorPhoto(i);};
const settle=()=>{if(reduced()){stop();++epoch;if(panel.open){if(phase==='closing'){panel.close();phase='closed';toggle.setAttribute('aria-expanded','false');}else phase='open';}}};mq.addEventListener('change',settle);document.querySelector('.reduce').addEventListener('click',settle);
window.paperMusic={open:openMusic,close:closeMusic,hide:stopForDialog,stats:()=>({open:panel.open,phase,playing:!audio.paused,audioElements:document.querySelectorAll('audio').length})};syncRuler();window.paperNavigation?.measure?.();
})();

// Historical writing is rendered as an archive, without creating new articles.
const siteMarkdown=window.markdownit({html:false,linkify:false,typographer:false});
const previousMarkdown=markdown;markdown=function(text){return index===1?'<div class="recovered-article">'+siteMarkdown.render(text)+'</div>':previousMarkdown(text);};
