import {mountCloudFlow} from './cloud-flow.js';
import {ShaderMount} from './assets/component-reference/paper-shaders/shader-mount.js';
import {grainGradientFragmentShader,GrainGradientShapes} from './assets/component-reference/paper-shaders/shaders/grain-gradient.js';
import {imageDitheringFragmentShader} from './assets/component-reference/paper-shaders/shaders/image-dithering.js';
import {getShaderNoiseTexture} from './assets/component-reference/paper-shaders/get-shader-noise-texture.js';
import {getShaderColorFromString as color} from './assets/component-reference/paper-shaders/get-shader-color-from-string.js';
const sizing={u_originX:.5,u_originY:.5,u_worldWidth:0,u_worldHeight:0,u_fit:2,u_scale:1,u_rotation:0,u_offsetX:0,u_offsetY:0};
const nextFrame=()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)));
(async()=>{
const stats={background:false,tile:false,photos:0,model:false,cloud:false,errors:[],scrollUpdates:0,materialWrites:0};window.paperPrint={stats:()=>({...stats})};
try{
// The hidden ground canvas used to repaint on every scroll. The visible body already owns this grain.
stats.background=true;
// Each new image is independently generated. The old sky is reserved for the podcast only.
const sources=window.PAPER_GENERATED_ASSETS;
if(sources){const baked=window.PAPER_MATERIAL_CACHE,processed={...(baked?.processed||{})},sizes={...(baked?.sizes||{})};stats.cached=!!baked;stats.shaderPasses=0;
async function processImage(key){if(processed[key])return;stats.shaderPasses++;const image=new Image();image.src=sources[key];await image.decode();sizes[key]=[image.width,image.height];const isCloud=key.startsWith('cloud-'),isSand=key.startsWith('sand-'),w=isCloud?960:(isSand?900:600),h=isCloud?1440:(key==='podcast-legacy'?240:(isSand?600:400));const sourceHost=document.createElement('div');sourceHost.className='print-tile-source';sourceHost.style.width=w+'px';sourceHost.style.height=h+'px';document.body.append(sourceHost);const filter=new ShaderMount(sourceHost,imageDitheringFragmentShader,{...sizing,u_image:image,u_colorFront:color('#729bb7'),u_colorBack:color('#e0eaf2'),u_colorHighlight:color('#f5f0e8'),u_pxSize:isCloud?1.5:(isSand?1:2),u_colorSteps:isCloud?12:24,u_originalColors:true,u_inverted:false,u_type:1},{alpha:false,preserveDrawingBuffer:true},0,0,1,w*h);await nextFrame();processed[key]=filter.canvasElement.toDataURL('image/png');filter.dispose();sourceHost.remove();}
for(const key of Object.keys(sources)){if(!processed[key]){processed[key]=sources[key];sizes[key]=[1024,1536];}}
const cloudKeys=['cloud-01','cloud-02','cloud-03'];
const sky=document.createElement('div');sky.className='cloud-sky';sky.setAttribute('aria-hidden','true');sky.style.backgroundImage='url("'+processed['cloud-01']+'")';document.body.prepend(sky);stats.cloud=true;const flowReady=mountCloudFlow(sky,cloudKeys.map(k=>processed[k]));
const materialObserver=typeof IntersectionObserver==='function'?new IntersectionObserver(entries=>{for(const entry of entries){if(!entry.isIntersecting)continue;const plane=entry.target;plane.style.backgroundImage='url("'+plane.dataset.textureUrl+'")';materialObserver.unobserve(plane);}},{rootMargin:'600px'}):null;
function mountMaterialPlanes(){const mappings=[...Array.from(document.querySelectorAll('.folio-sheet,.media-spread,.notebook-spread,.research-spread,.next-shelf'),(el,i)=>[el,el.dataset.material||(i%2?'sand-sage':'sand-blue')]),...Array.from(document.querySelectorAll('.book-pages,.context-workbench,.bench-inspector'),el=>[el,'sand-blue']),...Array.from(document.querySelectorAll('.repo-folder,.writing-list button,.next-grid button'),(el,i)=>[el,el.dataset.material||(i%2?'sand-sage':'sand-blue')]),...Array.from(document.querySelectorAll('.work-image'),(el,i)=>[el,i?'mineral-study':'terrace-study']),...[...document.querySelectorAll('.record-art')].map(el=>[el,'podcast-legacy']),...[...document.querySelectorAll('.design-art')].map(el=>[el,'sand-blue']),...[...document.querySelectorAll('.learning-paper')].map(el=>[el,'pond-study']),...Array.from(document.querySelectorAll('.asset-object'),(el,i)=>[el,el.dataset.materialKey||(el.dataset.assetType==='color'?'sand-blue':el.dataset.assetType==='paper'?'sand-sage':'sand-blue')])];for(const [host,key]of mappings){host.classList.add('pixel-plane');if(host.matches('.book-pages,.context-workbench,.bench-inspector,.repo-folder,.writing-list button,.next-grid button'))host.classList.add('sand-surface');host.dataset.material=key;let plane=host.querySelector(':scope>.pixel-window');if(!plane){plane=document.createElement('div');plane.className='pixel-window';plane.setAttribute('aria-hidden','true');host.append(plane);}if(plane.dataset.material!==key){stats.materialWrites++;plane.dataset.material=key;plane.dataset.textureUrl=processed[key];if(materialObserver)materialObserver.observe(plane);else plane.style.backgroundImage='url("'+processed[key]+'")';}const sample=host.querySelector(':scope>.sand-sample');if(sample&&sample.dataset.material!==key){stats.materialWrites++;sample.dataset.material=key;sample.style.backgroundImage='url("'+processed[key]+'")';}}}
mountMaterialPlanes();let pending=false;new MutationObserver(records=>{if(pending||!records.some(r=>[...r.addedNodes,...r.removedNodes].some(n=>n.nodeType===1)))return;pending=true;requestAnimationFrame(()=>{pending=false;mountMaterialPlanes();});}).observe(document.body,{childList:true,subtree:true});
const flow=await flowReady;window.paperCloud={...flow,stats:()=>({ready:true,sourceKeys:cloudKeys,sourceSizes:cloudKeys.map(k=>sizes[k]),grid:[960,1440],generated:Object.keys(processed).length-1,planes:document.querySelectorAll('.pixel-window').length,legacyUses:[...document.querySelectorAll('[data-material="podcast-legacy"]')].map(el=>el.className),...flow.stats()})};
window.paperMaterialPreview=processed;window.paperMaterialBake={processed,sizes};
window.paperGenerated={stats:()=>({sources:Object.keys(processed),sizes,placements:[...document.querySelectorAll('.pixel-plane')].map(el=>({class:el.className,material:el.dataset.material}))})};}

// The same image-dithering shader prints both a flat ink swatch and the real CC0 photographs.
const cache=window.PAPER_PRINT_CACHE;const halfUniforms=image=>({...sizing,u_image:image,u_colorFront:color('#406887'),u_colorBack:color('#dee6e9'),u_colorHighlight:color('#f0e6d5'),u_pxSize:1,u_colorSteps:7,u_originalColors:true,u_inverted:false,u_type:1});
const crops={ 'photo-city':[0,0],'photo-ocean':[1,0],'photo-forest':[3,0],'photo-mountain':[1,1]};const images=cache?.images||{};let tileURL=cache?.tile;
if(!tileURL){const flat=document.createElement('canvas');flat.width=192;flat.height=192;const ctx=flat.getContext('2d');ctx.fillStyle='#e0e8ef';ctx.fillRect(0,0,192,192);const flatImg=new Image();flatImg.src=flat.toDataURL();await flatImg.decode();const tileHost=document.createElement('div');tileHost.className='print-tile-source';tileHost.setAttribute('aria-hidden','true');document.body.append(tileHost);const tile=new ShaderMount(tileHost,imageDitheringFragmentShader,halfUniforms(flatImg),{alpha:false,preserveDrawingBuffer:true},0,0,1,192*192);await nextFrame();tileURL=tile.canvasElement.toDataURL('image/png');tile.dispose();tileHost.remove();}
document.documentElement.style.setProperty('--print-grain','url("'+tileURL+'")');stats.tile=true;
const original=document.querySelector('.atlas-photo'),bg=getComputedStyle(original).backgroundImage;const url=bg.match(/^url\(["']?(.*?)["']?\)$/)?.[1];if(!url)return;const atlas=new Image();atlas.src=url;await atlas.decode();
if(!cache){for(const [cls,[col,row]] of Object.entries(crops)){const cut=document.createElement('canvas');cut.width=600;cut.height=400;cut.getContext('2d').drawImage(atlas,col*atlas.width/4,row*atlas.height/6,atlas.width/4,atlas.height/6,0,0,600,400);const img=new Image();img.src=cut.toDataURL('image/png');await img.decode();const filterHost=document.createElement('div');filterHost.className='print-tile-source';filterHost.style.width='600px';filterHost.style.height='400px';document.body.append(filterHost);const filter=new ShaderMount(filterHost,imageDitheringFragmentShader,{...halfUniforms(img),u_pxSize:1.3,u_colorSteps:5},{alpha:false,preserveDrawingBuffer:true},0,0,1,600*400);await nextFrame();images[cls]=filter.canvasElement.toDataURL('image/jpeg',.92);filter.dispose();filterHost.remove();}}
function attach(){document.querySelectorAll('.atlas-photo').forEach(el=>{const cls=Object.keys(crops).find(c=>el.classList.contains(c));if(!cls||el.dataset.print===cls)return;el.querySelector('.print-photo')?.remove();el.style.position='relative';const layer=document.createElement('div');layer.className='print-photo';layer.style.cssText='background-image:url("'+images[cls]+'");background-size:cover;background-position:center;opacity:.92';el.append(layer);el.dataset.print=cls;stats.photos++;});}attach();let attachScheduled=false;new MutationObserver(()=>{if(attachScheduled)return;attachScheduled=true;requestAnimationFrame(()=>{attachScheduled=false;attach();});}).observe(document.body,{childList:true,subtree:true});
// Preserve the original model's UVs and geometry. The atlas alone receives random print dithering.
let printedAtlas=cache?.atlas;if(!printedAtlas){const atlasHost=document.createElement('div');atlasHost.className='print-tile-source';atlasHost.style.width='1024px';atlasHost.style.height='1024px';document.body.append(atlasHost);const modelPrint=new ShaderMount(atlasHost,imageDitheringFragmentShader,halfUniforms(atlas),{alpha:false,preserveDrawingBuffer:true},0,0,1,1024*1024);await nextFrame();printedAtlas=modelPrint.canvasElement.toDataURL('image/jpeg',.95);modelPrint.dispose();atlasHost.remove();}window.PAPER_PRINT_BAKED={tile:tileURL,images,atlas:printedAtlas};window.paperApplyPrintedModel=async()=>{if(window.setPaperPrintTexture){await window.setPaperPrintTexture(printedAtlas);stats.model=true;}};await window.paperApplyPrintedModel();
}catch(e){stats.errors.push(e.message);console.warn('Print material fallback:',e.message);}
})();
