import * as THREE from 'three';
import {GLTFLoader} from 'three/examples/jsm/loaders/GLTFLoader.js';
import {RoomEnvironment} from 'three/examples/jsm/environments/RoomEnvironment.js';
try {
const el=document.querySelector('.stage'),reduced=matchMedia('(prefers-reduced-motion:reduce)');let front=0,selected=-1,manualReduce=false,ready=false,moving=0,dirty=true,spin={x:0,y:0};const pages=[];
const renderer=new THREE.WebGLRenderer({antialias:true,alpha:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setClearColor(0xffffff,0);renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFShadowMap;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=.92;el.append(renderer.domElement);renderer.domElement.addEventListener('webglcontextlost',e=>{e.preventDefault();ready=false;window.paperFlatFallback?.();},{once:true});
const scene=new THREE.Scene(),group=new THREE.Group(),camera=new THREE.PerspectiveCamera(34,1,.1,30);camera.position.set(0,.2,6.0);camera.lookAt(0,0,0);scene.add(group);const pmrem=new THREE.PMREMGenerator(renderer);scene.environment=pmrem.fromScene(new RoomEnvironment(),.04).texture;scene.add(new THREE.HemisphereLight(0xffffff,0x9dabb2,.45));const light=new THREE.DirectionalLight(0xffffff,1.85);light.position.set(-3,5,6);light.castShadow=true;light.shadow.mapSize.set(2048,2048);Object.assign(light.shadow.camera,{left:-5,right:5,top:5,bottom:-5,near:.1,far:20});light.shadow.radius=8;light.shadow.normalBias=.004;scene.add(light);const floor=new THREE.Mesh(new THREE.PlaneGeometry(30,30),new THREE.ShadowMaterial({opacity:.035}));floor.rotation.x=-Math.PI/2;floor.position.y=-1.43;floor.receiveShadow=true;scene.add(floor);
function layout(rate){pages.forEach((p,i)=>{const rank=(i-front+3)%3;const home=[[-.1,-.07,.50],[.42,.51,-.2],[-.42,-.38,-.35]][rank];let [x,y,z]=home,ry=[-.10,.12,.16][rank],rz=[-.08,.08,-.17][rank],scale=1;if(selected===i){x=0;y=0;z=1.05;ry=rz=0;scale=1.03;}else if(selected>=0){x=rank===1?.56:-.56;y=rank===1?.90:-.78;z=rank===1?-.24:-.42;scale=.86;}p.root.position.lerp(new THREE.Vector3(x,y,z),rate);p.root.scale.lerp(new THREE.Vector3(scale,scale,scale),rate);p.root.rotation.y+=(ry-p.root.rotation.y)*rate;p.root.rotation.z+=(rz-p.root.rotation.z)*rate;});}
function cycle(delta){const next=(front+delta+3)%3;if(selected>=0){window.selectPaper(next);return;}front=next;moving=performance.now()+740;document.querySelector('.card-status').textContent=String(front+1).padStart(2,'0')+' / 03';el.dataset.front=String(front);}
window.setFrontPaper=i=>cycle(i-front);document.querySelector('.card-prev').onclick=()=>cycle(-1);document.querySelector('.card-next').onclick=()=>cycle(1);el.tabIndex=0;el.setAttribute('role','group');el.setAttribute('aria-label','纸卡：左右键切换，Enter 展开；也可以左右拖动');el.addEventListener('keydown',e=>{if(e.key==='ArrowLeft'||e.key==='ArrowRight'){e.preventDefault();cycle(e.key==='ArrowRight'?1:-1);}if(e.key==='Enter'){window.selectPaper(front);}});let down=null,dragged=false;el.addEventListener('pointerdown',e=>{down={x:e.clientX,y:e.clientY};dragged=false;el.setPointerCapture(e.pointerId);});el.addEventListener('pointerup',e=>{if(!down)return;const dx=e.clientX-down.x,dy=e.clientY-down.y;dragged=Math.abs(dx)>35&&Math.abs(dx)>Math.abs(dy);if(dragged)cycle(dx<0?1:-1);down=null;});el.addEventListener('pointercancel',()=>{down=null;dragged=true;});
function resize(){const r={width:el.clientWidth,height:el.clientHeight};renderer.setSize(r.width,r.height);camera.aspect=r.width/r.height;camera.position.z=r.width<600?7:6;camera.updateProjectionMatrix();dirty=true;}new ResizeObserver(resize).observe(el);let lastRender=0;function loop(now){if(ready&&(dirty||moving>0||Math.abs(group.rotation.y-spin.y)>.0001||Math.abs(group.rotation.x-spin.x)>.0001)){const instant=reduced.matches||manualReduce,dt=Math.max(1,lastRender?Math.min(150,now-lastRender):16),settled=moving>0&&now>=moving,rate=instant||settled?1:1-Math.exp(-dt/120);layout(rate);group.rotation.y+=(spin.y-group.rotation.y)*rate;group.rotation.x+=(spin.x-group.rotation.x)*rate;renderer.render(scene,camera);if(settled)moving=0;dirty=false;lastRender=now;}requestAnimationFrame(loop);}requestAnimationFrame(loop);el.addEventListener('pointermove',e=>{if(reduced.matches||manualReduce||e.pointerType==='touch')return;const r=el.getBoundingClientRect();spin={x:((e.clientY-r.top)/r.height-.5)*.025,y:((e.clientX-r.left)/r.width-.5)*.085};dirty=true;});el.addEventListener('pointerleave',()=>{spin={x:0,y:0};moving=performance.now()+650;});const ray=new THREE.Raycaster(),pointer=new THREE.Vector2();el.addEventListener('click',e=>{if(!ready||dragged){dragged=false;return;}const r=el.getBoundingClientRect();pointer.set((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1);ray.setFromCamera(pointer,camera);const hit=ray.intersectObjects(pages.map(p=>p.mesh),true)[0];if(hit){const i=pages.findIndex(p=>p.mesh===hit.object);if(i>=0&&i!==front){cycle(i-front);}else{window.selectPaper(i<0?front:i);}}});window.selectPaper=i=>{i=((Math.round(i)%3)+3)%3;front=i;el.dataset.front=String(front);document.querySelector(".card-status").textContent=String(front+1).padStart(2,"0")+" / 03";selected=i;moving=performance.now()+740;window.onPaperSelect?.(i);};window.closePaper=()=>{selected=-1;moving=performance.now()+740;};window.setPaperReduced=v=>{manualReduce=v;spin={x:0,y:0};moving=performance.now()+40;};window.setPaperLanguage=()=>{};reduced.addEventListener('change',()=>{spin={x:0,y:0};moving=performance.now()+40;});
(async()=>{try{const loader=new GLTFLoader();const g=await loader.parseAsync(JSON.stringify(window.PAPER_MODEL),'');const meshes=[];g.scene.traverse(o=>{if(o.isMesh)meshes.push(o);});console.log('Source model meshes',meshes.length);for(const n of[1,3,5]){const mesh=meshes[n].clone();mesh.geometry=mesh.geometry.clone();mesh.position.set(0,0,0);mesh.scale.setScalar(18);mesh.material=mesh.material.clone();mesh.material.side=THREE.DoubleSide;mesh.material.map.anisotropy=Math.min(renderer.capabilities.getMaxAnisotropy(),8);mesh.castShadow=true;mesh.receiveShadow=true;const root=new THREE.Group();root.add(mesh);group.add(root);pages.push({root,mesh});}ready=true;window.paperApplyPrintedModel?.();el.dataset.front='0';layout(1);resize();document.querySelector('.loading').hidden=true;document.body.dataset.ready='true';}catch(e){window.paperFlatFallback?.();console.warn(e);document.querySelector('.loading').textContent='模型暂时无法加载，请使用内容入口。';window.selectPaper=i=>window.onPaperSelect?.(i);}})();

window.setPaperPrintTexture=async url=>{const texture=await new THREE.TextureLoader().loadAsync(url);texture.flipY=false;texture.colorSpace=THREE.SRGBColorSpace;texture.anisotropy=Math.min(renderer.capabilities.getMaxAnisotropy(),8);if(!ready){await new Promise((resolve,reject)=>{const start=performance.now();const timer=setInterval(()=>{if(ready){clearInterval(timer);resolve();}else if(performance.now()-start>10000){clearInterval(timer);texture.dispose();reject(new Error('Print texture unavailable; use the content entry.'));}},50);});}pages.forEach(p=>{p.mesh.material.map=texture;p.mesh.material.needsUpdate=true;});dirty=true;moving=performance.now()+40;};

window.paperModelMotion={stats:()=>({ready,front,selected,moving:moving>performance.now(),poses:pages.map(p=>({x:p.root.position.x,y:p.root.position.y,z:p.root.position.z}))})};

}catch(error){console.warn("3D fallback:",error.message);window.paperFlatFallback?.();}
