const look=document.querySelector('.look'),reader=document.querySelector('.reader');let originScroll=0,lang=window.PAPER_INITIAL_LANG||'zh',lastFocus=null,index=-1,userReduce=false,detail=null;const mq=matchMedia('(prefers-reduced-motion:reduce)'),reduced=()=>mq.matches||userReduce,content=window.SITE_CONTENT;
const words={zh:{works:'作品',posts:'文字',about:'探索',back:'返回列表',prev:'上一个',next:'下一个',video:'加载原项目示例视频 ↗',link:'项目仓库 ↗',date:'日期',client:'客户',role:'角色',missing:'这一条暂未提供英文版，已返回列表。'},en:{works:'Works',posts:'Writing',about:'Explore',back:'Back to list',prev:'Previous',next:'Next',video:'Load existing sample video ↗',link:'Project repository ↗',date:'Date',client:'Client',role:'Role',missing:'This entry has no translation. Returned to the list.'}};
function animate(el,frames,opts){if(reduced()){Object.entries(frames).forEach(([k,v])=>el.style[k]=Array.isArray(v)?v.at(-1):v);return;}Motion.animate(el,frames,opts);}
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function markdown(s){return s.split(/\n\s*\n/).map(block=>'<p>'+esc(block.replace(/\n/g,' ')).replace(/!\[([^\]]*)\]\((data:image\/[^)]+)\)/g,'<img src="$2" alt="$1" data-large>').replace(/\*\*([^*]+)\*\*/g,'<strong>$1</strong>')+'</p>').join('');}
function fill(){const w=words[lang],kind=index===0?'works':'posts',list=index===2?[]:content[lang][kind],root=document.querySelector('.reader-list');root.innerHTML='';document.querySelector('#reader-title').textContent=index===2?w.about:w[kind];document.querySelector('.reader-note').textContent='';if(detail){const item=list.find(e=>e.slug===detail.slug);if(!item){detail=null;document.querySelector('.reader-note').textContent=w.missing;}else{document.querySelector('#reader-title').textContent=item.title.replace(/^(占位作品|占位文章)[:：]/,'').replace(/^(Placeholder post|Placeholder)[:：]\s*/i,'');const li=document.createElement('li');li.className='reading-detail';li.innerHTML='<div class="meta-line">'+[item.status,item.date,item.client&&w.client+' · '+item.client,item.role&&w.role+' · '+item.role].filter(Boolean).map(esc).join('<br>')+'</div><p>'+esc(item.summary)+'</p>'+markdown(item.body)+(item.video?'<button class="video-load">'+w.video+'</button>':'')+(item.link?'<a target="_blank" rel="noopener" href="'+esc(item.link)+'">'+w.link+'</a>':'')+'<div class="detail-pager"></div>';root.append(li);li.querySelector('.video-load')?.addEventListener('click',e=>{const id=new URL(item.video).pathname.split('/').filter(Boolean)[0];const iframe=document.createElement('iframe');iframe.src='https://player.vimeo.com/video/'+encodeURIComponent(id);iframe.title=item.title;iframe.allow='fullscreen; picture-in-picture';iframe.allowFullscreen=true;e.currentTarget.replaceWith(iframe);});li.querySelectorAll('[data-large]').forEach(img=>img.onclick=()=>{const dialog=document.querySelector('.image-dialog');dialog.querySelector('img').src=img.src;dialog.querySelector('img').alt=img.alt;dialog.showModal();});const pos=list.indexOf(item),pager=li.querySelector('.detail-pager');for(const [label,entry] of [[w.prev,list[pos-1]],[w.back,null],[w.next,list[pos+1]]]){if(label!==w.back&&!entry)continue;const b=document.createElement('button');b.textContent=label;b.onclick=()=>{detail=entry?{slug:entry.slug}:null;fill();reader.scrollTop=0;};pager.append(b);}return;}}
 for(const item of list){const li=document.createElement('li'),b=document.createElement('button'),small=document.createElement('p');b.textContent=item.title.replace(/^(占位作品|占位文章)[:：]/,'').replace(/^(Placeholder post|Placeholder)[:：]\s*/i,'')+' ↗';small.textContent=item.date;b.onclick=()=>{detail={slug:item.slug};fill();reader.scrollTop=0;};li.append(b,small);root.append(li);}if(index===2){for(const a of document.querySelectorAll('.section-map a:not([hidden])')){const li=document.createElement('li'),b=document.createElement('button');b.textContent=a.dataset[lang]+' ↗';b.onclick=()=>{close({restoreScroll:false,immediate:true});document.querySelector(a.getAttribute('href')).scrollIntoView({behavior:reduced()?'instant':'smooth'});};li.append(b);root.append(li);}}}
let readerMotion=null,readerEpoch=0,readerPhase='closed';
function stopReaderMotion(){readerMotion?.stop();readerMotion=null;}
function moveReader(frames,duration,done){stopReaderMotion();const epoch=++readerEpoch;if(reduced()){Object.entries(frames).forEach(([key,value])=>reader.style[key]=Array.isArray(value)?value.at(-1):value);done?.();return;}readerMotion=Motion.animate(reader,frames,{duration,ease:[.2,0,0,1]});readerMotion.then(()=>{if(epoch===readerEpoch){readerMotion=null;done?.();}});}
window.onPaperSelect=i=>{const retainedFocus=reader.contains(document.activeElement)?document.activeElement:null;if(index<0){originScroll=scrollY;lastFocus=document.activeElement;}window.scrollTo({top:0,behavior:reduced()?'instant':'smooth'});index=i;fill();reader.inert=false;readerPhase='opening';look.classList.add('open');reader.scrollTop=0;moveReader({opacity:[0,1],transform:innerWidth<=560?['translateY(24px) scale(.985)','translateY(0) scale(1)']:['translateX(28px) scale(.985)','translateX(0) scale(1)']},.42,()=>readerPhase='open');if(!retainedFocus?.isConnected)document.querySelector('.close').focus({preventScroll:true});};
function close(options={}){if(index<0)return;const {restoreScroll=true,immediate=false}=options;reader.inert=true;readerPhase='closing';window.closePaper?.();const finish=()=>{look.classList.remove('open');readerPhase='closed';index=-1;detail=null;if(restoreScroll){window.scrollTo({top:originScroll,behavior:reduced()?'instant':'smooth'});lastFocus?.focus({preventScroll:true});}};if(immediate){stopReaderMotion();++readerEpoch;reader.style.opacity='0';reader.style.transform='none';finish();}else moveReader({opacity:0,transform:innerWidth<=560?'translateY(18px) scale(.985)':'translateX(24px) scale(.985)'},.32,finish);}
window.paperReader={stats:()=>({phase:readerPhase,index,animating:!!readerMotion})};
document.querySelector('.close').onclick=()=>close();document.querySelector('.brand').onclick=()=>{close({restoreScroll:false,immediate:true});document.querySelector('.look').scrollIntoView({behavior:reduced()?'instant':'smooth'});};
document.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>{detail=null;window.selectPaper?.(+b.dataset.open);});document.querySelectorAll('[data-entry],[data-post]').forEach(b=>b.onclick=()=>{detail={slug:b.dataset.entry||b.dataset.post};window.selectPaper?.(b.dataset.entry?0:1);});document.querySelectorAll('[data-scroll]').forEach(b=>b.onclick=()=>{close({restoreScroll:false,immediate:true});goChapter(chapterIds.indexOf(b.dataset.scroll));});
document.addEventListener('keydown',e=>{if(window.paperGalleryOpen||document.querySelector('.image-dialog').open||document.querySelector('.explore-dialog').open||document.querySelector('.recovered-dialog')?.open)return;if(e.key==='Escape')close();if(e.key==='Tab'&&look.classList.contains('open')){const buttons=[...reader.querySelectorAll('button,a,input,[role=slider],[tabindex="0"]')];if(e.shiftKey&&(document.activeElement===buttons[0]||!reader.contains(document.activeElement))){e.preventDefault();buttons.at(-1).focus();}else if(!e.shiftKey&&(document.activeElement===buttons.at(-1)||!reader.contains(document.activeElement))){e.preventDefault();buttons[0].focus();}}});
document.querySelector('.language').onclick=()=>{lang=lang==='zh'?'en':'zh';document.documentElement.lang=lang==='zh'?'zh-CN':'en';document.querySelectorAll('[data-zh]').forEach(e=>e.textContent=e.dataset[lang]);document.querySelector('.language').textContent=lang==='zh'?'EN':'中';document.querySelectorAll('.zh-only').forEach(e=>e.hidden=lang==='en');if(index>=0)fill();window.setPaperLanguage?.(lang);};
document.querySelector('.reduce').onclick=e=>{userReduce=!userReduce;document.body.classList.toggle('motion-off',userReduce);e.currentTarget.setAttribute('aria-pressed',String(userReduce));window.setPaperReduced?.(userReduce);if(userReduce)document.getAnimations().forEach(a=>{if(a.effect?.getComputedTiming().endTime===Infinity){try{a.commitStyles();}catch{}a.cancel();}else a.finish();});};
document.querySelector('.image-dialog button').onclick=()=>document.querySelector('.image-dialog').close();